/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.ide;

import br.ufscar.dc.compiladores.t5.T5RuntimeModule;
import br.ufscar.dc.compiladores.t5.t5RuntimeModule;
import br.ufscar.dc.compiladores.alguma.T5StandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class t5IdeSetup extends T5StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new t5RuntimeModule(), new T5IdeModule()));
	}
	
}
