/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class T5StandaloneSetup extends T5StandaloneSetupGenerated {

	public static void doSetup() {
		new T5StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
