/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.parser.antlr;

import br.ufscar.dc.compiladores.t5.parser.antlr.internal.InternalT5Parser;
import br.ufscar.dc.compiladores.t5.services.T5GrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class T5Parser extends AbstractAntlrParser {

	@Inject
	private T5GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	

	@Override
	protected InternalT5Parser createParser(XtextTokenStream stream) {
		return new InternalT5Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Programa";
	}

	public T5GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(T5GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
