/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class T5fAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/ufscar/dc/compiladores/at5/parser/antlr/internal/InternalT5f.tokens");
	}
}
