/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.parser.antlr;

import br.ufscar.dc.compiladores.at5.parser.antlr.internal.InternalT5fParser;
import br.ufscar.dc.compiladores.at5.services.T5fGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class T5fParser extends AbstractAntlrParser {

	@Inject
	private T5fGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalT5fParser createParser(XtextTokenStream stream) {
		return new InternalT5fParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Programa";
	}

	public T5fGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(T5fGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
