/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class T5fStandaloneSetup extends T5fStandaloneSetupGenerated {

	public static void doSetup() {
		new T5fStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
