/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractT5fScopeProvider extends DelegatingScopeProvider {
}
