/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Chamada</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.ComandoChamada#getName <em>Name</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.ComandoChamada#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getComandoChamada()
 * @model
 * @generated
 */
public interface ComandoChamada extends Comando
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getComandoChamada_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoChamada#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.at5.t5f.Expressao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getComandoChamada_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expressao> getArgs();

} // ComandoChamada
