/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getComando()
 * @model
 * @generated
 */
public interface Comando extends EObject
{
} // Comando
