/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaracao Global</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal#getParametros <em>Parametros</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal#getCorpo <em>Corpo</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal#getTipoRetorno <em>Tipo Retorno</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getDeclaracaoGlobal()
 * @model
 * @generated
 */
public interface DeclaracaoGlobal extends Declaracao
{
  /**
   * Returns the value of the '<em><b>Parametros</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametros</em>' containment reference.
   * @see #setParametros(Parametros)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getDeclaracaoGlobal_Parametros()
   * @model containment="true"
   * @generated
   */
  Parametros getParametros();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal#getParametros <em>Parametros</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parametros</em>' containment reference.
   * @see #getParametros()
   * @generated
   */
  void setParametros(Parametros value);

  /**
   * Returns the value of the '<em><b>Corpo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Corpo</em>' containment reference.
   * @see #setCorpo(Corpo)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getDeclaracaoGlobal_Corpo()
   * @model containment="true"
   * @generated
   */
  Corpo getCorpo();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal#getCorpo <em>Corpo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Corpo</em>' containment reference.
   * @see #getCorpo()
   * @generated
   */
  void setCorpo(Corpo value);

  /**
   * Returns the value of the '<em><b>Tipo Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Retorno</em>' containment reference.
   * @see #setTipoRetorno(TipoEstendido)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getDeclaracaoGlobal_TipoRetorno()
   * @model containment="true"
   * @generated
   */
  TipoEstendido getTipoRetorno();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal#getTipoRetorno <em>Tipo Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Retorno</em>' containment reference.
   * @see #getTipoRetorno()
   * @generated
   */
  void setTipoRetorno(TipoEstendido value);

} // DeclaracaoGlobal
