/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dimensao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Dimensao#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getDimensao()
 * @model
 * @generated
 */
public interface Dimensao extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(ExpressaoAritmetica)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getDimensao_Exp()
   * @model containment="true"
   * @generated
   */
  ExpressaoAritmetica getExp();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.Dimensao#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(ExpressaoAritmetica value);

} // Dimensao
