/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Expressao#getLogicos <em>Logicos</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Expressao#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getExpressao()
 * @model
 * @generated
 */
public interface Expressao extends EObject
{
  /**
   * Returns the value of the '<em><b>Logicos</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.at5.t5f.TermoLogico}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logicos</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getExpressao_Logicos()
   * @model containment="true"
   * @generated
   */
  EList<TermoLogico> getLogicos();

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getExpressao_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

} // Expressao
