/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identificador</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Identificador#getName <em>Name</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Identificador#getParts <em>Parts</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Identificador#getDimensoes <em>Dimensoes</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getIdentificador()
 * @model
 * @generated
 */
public interface Identificador extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getIdentificador_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.Identificador#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parts</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parts</em>' attribute list.
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getIdentificador_Parts()
   * @model unique="false"
   * @generated
   */
  EList<String> getParts();

  /**
   * Returns the value of the '<em><b>Dimensoes</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.at5.t5f.Dimensao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimensoes</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getIdentificador_Dimensoes()
   * @model containment="true"
   * @generated
   */
  EList<Dimensao> getDimensoes();

} // Identificador
