/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selecao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Selecao#getItens <em>Itens</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.Selecao#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getSelecao()
 * @model
 * @generated
 */
public interface Selecao extends EObject
{
  /**
   * Returns the value of the '<em><b>Itens</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.at5.t5f.ItemSelecao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Itens</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getSelecao_Itens()
   * @model containment="true"
   * @generated
   */
  EList<ItemSelecao> getItens();

  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.at5.t5f.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getSelecao_Comandos()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandos();

} // Selecao
