/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termo Logico</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.TermoLogico#isNao <em>Nao</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.TermoLogico#getRel <em>Rel</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getTermoLogico()
 * @model
 * @generated
 */
public interface TermoLogico extends EObject
{
  /**
   * Returns the value of the '<em><b>Nao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nao</em>' attribute.
   * @see #setNao(boolean)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getTermoLogico_Nao()
   * @model
   * @generated
   */
  boolean isNao();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.TermoLogico#isNao <em>Nao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nao</em>' attribute.
   * @see #isNao()
   * @generated
   */
  void setNao(boolean value);

  /**
   * Returns the value of the '<em><b>Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel</em>' containment reference.
   * @see #setRel(ExpressaoRelacional)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getTermoLogico_Rel()
   * @model containment="true"
   * @generated
   */
  ExpressaoRelacional getRel();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.TermoLogico#getRel <em>Rel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel</em>' containment reference.
   * @see #getRel()
   * @generated
   */
  void setRel(ExpressaoRelacional value);

} // TermoLogico
