/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tipo Estendido</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.TipoEstendido#getBasic <em>Basic</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.TipoEstendido#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getTipoEstendido()
 * @model
 * @generated
 */
public interface TipoEstendido extends EObject
{
  /**
   * Returns the value of the '<em><b>Basic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basic</em>' attribute.
   * @see #setBasic(String)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getTipoEstendido_Basic()
   * @model
   * @generated
   */
  String getBasic();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.TipoEstendido#getBasic <em>Basic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basic</em>' attribute.
   * @see #getBasic()
   * @generated
   */
  void setBasic(String value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Declaracao)
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#getTipoEstendido_Ref()
   * @model
   * @generated
   */
  Declaracao getRef();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.at5.t5f.TipoEstendido#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Declaracao value);

} // TipoEstendido
