/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.ui.tests;

import br.ufscar.dc.compiladores.at5.ui.internal.At5Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class T5fUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return At5Activator.getInstance().getInjector("br.ufscar.dc.compiladores.at5.T5f");
	}

}
