/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Comando;
import br.ufscar.dc.compiladores.at5.t5f.ComandoPara;
import br.ufscar.dc.compiladores.at5.t5f.ExpressaoAritmetica;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comando Para</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ComandoParaImpl#getVar <em>Var</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ComandoParaImpl#getInicio <em>Inicio</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ComandoParaImpl#getFim <em>Fim</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ComandoParaImpl#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComandoParaImpl extends ComandoImpl implements ComandoPara
{
  /**
   * The default value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected static final String VAR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected String var = VAR_EDEFAULT;

  /**
   * The cached value of the '{@link #getInicio() <em>Inicio</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInicio()
   * @generated
   * @ordered
   */
  protected ExpressaoAritmetica inicio;

  /**
   * The cached value of the '{@link #getFim() <em>Fim</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFim()
   * @generated
   * @ordered
   */
  protected ExpressaoAritmetica fim;

  /**
   * The cached value of the '{@link #getComandos() <em>Comandos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandos()
   * @generated
   * @ordered
   */
  protected EList<Comando> comandos;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandoParaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5fPackage.Literals.COMANDO_PARA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVar(String newVar)
  {
    String oldVar = var;
    var = newVar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.COMANDO_PARA__VAR, oldVar, var));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoAritmetica getInicio()
  {
    return inicio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInicio(ExpressaoAritmetica newInicio, NotificationChain msgs)
  {
    ExpressaoAritmetica oldInicio = inicio;
    inicio = newInicio;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.COMANDO_PARA__INICIO, oldInicio, newInicio);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInicio(ExpressaoAritmetica newInicio)
  {
    if (newInicio != inicio)
    {
      NotificationChain msgs = null;
      if (inicio != null)
        msgs = ((InternalEObject)inicio).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.COMANDO_PARA__INICIO, null, msgs);
      if (newInicio != null)
        msgs = ((InternalEObject)newInicio).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.COMANDO_PARA__INICIO, null, msgs);
      msgs = basicSetInicio(newInicio, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.COMANDO_PARA__INICIO, newInicio, newInicio));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoAritmetica getFim()
  {
    return fim;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFim(ExpressaoAritmetica newFim, NotificationChain msgs)
  {
    ExpressaoAritmetica oldFim = fim;
    fim = newFim;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.COMANDO_PARA__FIM, oldFim, newFim);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFim(ExpressaoAritmetica newFim)
  {
    if (newFim != fim)
    {
      NotificationChain msgs = null;
      if (fim != null)
        msgs = ((InternalEObject)fim).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.COMANDO_PARA__FIM, null, msgs);
      if (newFim != null)
        msgs = ((InternalEObject)newFim).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.COMANDO_PARA__FIM, null, msgs);
      msgs = basicSetFim(newFim, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.COMANDO_PARA__FIM, newFim, newFim));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getComandos()
  {
    if (comandos == null)
    {
      comandos = new EObjectContainmentEList<Comando>(Comando.class, this, T5fPackage.COMANDO_PARA__COMANDOS);
    }
    return comandos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_PARA__INICIO:
        return basicSetInicio(null, msgs);
      case T5fPackage.COMANDO_PARA__FIM:
        return basicSetFim(null, msgs);
      case T5fPackage.COMANDO_PARA__COMANDOS:
        return ((InternalEList<?>)getComandos()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_PARA__VAR:
        return getVar();
      case T5fPackage.COMANDO_PARA__INICIO:
        return getInicio();
      case T5fPackage.COMANDO_PARA__FIM:
        return getFim();
      case T5fPackage.COMANDO_PARA__COMANDOS:
        return getComandos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_PARA__VAR:
        setVar((String)newValue);
        return;
      case T5fPackage.COMANDO_PARA__INICIO:
        setInicio((ExpressaoAritmetica)newValue);
        return;
      case T5fPackage.COMANDO_PARA__FIM:
        setFim((ExpressaoAritmetica)newValue);
        return;
      case T5fPackage.COMANDO_PARA__COMANDOS:
        getComandos().clear();
        getComandos().addAll((Collection<? extends Comando>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_PARA__VAR:
        setVar(VAR_EDEFAULT);
        return;
      case T5fPackage.COMANDO_PARA__INICIO:
        setInicio((ExpressaoAritmetica)null);
        return;
      case T5fPackage.COMANDO_PARA__FIM:
        setFim((ExpressaoAritmetica)null);
        return;
      case T5fPackage.COMANDO_PARA__COMANDOS:
        getComandos().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_PARA__VAR:
        return VAR_EDEFAULT == null ? var != null : !VAR_EDEFAULT.equals(var);
      case T5fPackage.COMANDO_PARA__INICIO:
        return inicio != null;
      case T5fPackage.COMANDO_PARA__FIM:
        return fim != null;
      case T5fPackage.COMANDO_PARA__COMANDOS:
        return comandos != null && !comandos.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (var: ");
    result.append(var);
    result.append(')');
    return result.toString();
  }

} //ComandoParaImpl
