/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Comando;
import br.ufscar.dc.compiladores.at5.t5f.ComandoSe;
import br.ufscar.dc.compiladores.at5.t5f.Expressao;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comando Se</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ComandoSeImpl#getCond <em>Cond</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ComandoSeImpl#getComandos <em>Comandos</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ComandoSeImpl#getComandosElse <em>Comandos Else</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComandoSeImpl extends ComandoImpl implements ComandoSe
{
  /**
   * The cached value of the '{@link #getCond() <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCond()
   * @generated
   * @ordered
   */
  protected Expressao cond;

  /**
   * The cached value of the '{@link #getComandos() <em>Comandos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandos()
   * @generated
   * @ordered
   */
  protected EList<Comando> comandos;

  /**
   * The cached value of the '{@link #getComandosElse() <em>Comandos Else</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandosElse()
   * @generated
   * @ordered
   */
  protected EList<Comando> comandosElse;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandoSeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5fPackage.Literals.COMANDO_SE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expressao getCond()
  {
    return cond;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCond(Expressao newCond, NotificationChain msgs)
  {
    Expressao oldCond = cond;
    cond = newCond;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.COMANDO_SE__COND, oldCond, newCond);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCond(Expressao newCond)
  {
    if (newCond != cond)
    {
      NotificationChain msgs = null;
      if (cond != null)
        msgs = ((InternalEObject)cond).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.COMANDO_SE__COND, null, msgs);
      if (newCond != null)
        msgs = ((InternalEObject)newCond).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.COMANDO_SE__COND, null, msgs);
      msgs = basicSetCond(newCond, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.COMANDO_SE__COND, newCond, newCond));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getComandos()
  {
    if (comandos == null)
    {
      comandos = new EObjectContainmentEList<Comando>(Comando.class, this, T5fPackage.COMANDO_SE__COMANDOS);
    }
    return comandos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getComandosElse()
  {
    if (comandosElse == null)
    {
      comandosElse = new EObjectContainmentEList<Comando>(Comando.class, this, T5fPackage.COMANDO_SE__COMANDOS_ELSE);
    }
    return comandosElse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_SE__COND:
        return basicSetCond(null, msgs);
      case T5fPackage.COMANDO_SE__COMANDOS:
        return ((InternalEList<?>)getComandos()).basicRemove(otherEnd, msgs);
      case T5fPackage.COMANDO_SE__COMANDOS_ELSE:
        return ((InternalEList<?>)getComandosElse()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_SE__COND:
        return getCond();
      case T5fPackage.COMANDO_SE__COMANDOS:
        return getComandos();
      case T5fPackage.COMANDO_SE__COMANDOS_ELSE:
        return getComandosElse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_SE__COND:
        setCond((Expressao)newValue);
        return;
      case T5fPackage.COMANDO_SE__COMANDOS:
        getComandos().clear();
        getComandos().addAll((Collection<? extends Comando>)newValue);
        return;
      case T5fPackage.COMANDO_SE__COMANDOS_ELSE:
        getComandosElse().clear();
        getComandosElse().addAll((Collection<? extends Comando>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_SE__COND:
        setCond((Expressao)null);
        return;
      case T5fPackage.COMANDO_SE__COMANDOS:
        getComandos().clear();
        return;
      case T5fPackage.COMANDO_SE__COMANDOS_ELSE:
        getComandosElse().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.COMANDO_SE__COND:
        return cond != null;
      case T5fPackage.COMANDO_SE__COMANDOS:
        return comandos != null && !comandos.isEmpty();
      case T5fPackage.COMANDO_SE__COMANDOS_ELSE:
        return comandosElse != null && !comandosElse.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ComandoSeImpl
