/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Dimensao;
import br.ufscar.dc.compiladores.at5.t5f.Identificador;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Identificador</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.IdentificadorImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.IdentificadorImpl#getParts <em>Parts</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.IdentificadorImpl#getDimensoes <em>Dimensoes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IdentificadorImpl extends MinimalEObjectImpl.Container implements Identificador
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParts() <em>Parts</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParts()
   * @generated
   * @ordered
   */
  protected EList<String> parts;

  /**
   * The cached value of the '{@link #getDimensoes() <em>Dimensoes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDimensoes()
   * @generated
   * @ordered
   */
  protected EList<Dimensao> dimensoes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IdentificadorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5fPackage.Literals.IDENTIFICADOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.IDENTIFICADOR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getParts()
  {
    if (parts == null)
    {
      parts = new EDataTypeEList<String>(String.class, this, T5fPackage.IDENTIFICADOR__PARTS);
    }
    return parts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Dimensao> getDimensoes()
  {
    if (dimensoes == null)
    {
      dimensoes = new EObjectContainmentEList<Dimensao>(Dimensao.class, this, T5fPackage.IDENTIFICADOR__DIMENSOES);
    }
    return dimensoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5fPackage.IDENTIFICADOR__DIMENSOES:
        return ((InternalEList<?>)getDimensoes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5fPackage.IDENTIFICADOR__NAME:
        return getName();
      case T5fPackage.IDENTIFICADOR__PARTS:
        return getParts();
      case T5fPackage.IDENTIFICADOR__DIMENSOES:
        return getDimensoes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5fPackage.IDENTIFICADOR__NAME:
        setName((String)newValue);
        return;
      case T5fPackage.IDENTIFICADOR__PARTS:
        getParts().clear();
        getParts().addAll((Collection<? extends String>)newValue);
        return;
      case T5fPackage.IDENTIFICADOR__DIMENSOES:
        getDimensoes().clear();
        getDimensoes().addAll((Collection<? extends Dimensao>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.IDENTIFICADOR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case T5fPackage.IDENTIFICADOR__PARTS:
        getParts().clear();
        return;
      case T5fPackage.IDENTIFICADOR__DIMENSOES:
        getDimensoes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.IDENTIFICADOR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case T5fPackage.IDENTIFICADOR__PARTS:
        return parts != null && !parts.isEmpty();
      case T5fPackage.IDENTIFICADOR__DIMENSOES:
        return dimensoes != null && !dimensoes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", parts: ");
    result.append(parts);
    result.append(')');
    return result.toString();
  }

} //IdentificadorImpl
