/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Identificador;
import br.ufscar.dc.compiladores.at5.t5f.Parametro;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;
import br.ufscar.dc.compiladores.at5.t5f.TipoEstendido;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parametro</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ParametroImpl#getIds <em>Ids</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ParametroImpl#getTipoParam <em>Tipo Param</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParametroImpl extends MinimalEObjectImpl.Container implements Parametro
{
  /**
   * The cached value of the '{@link #getIds() <em>Ids</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIds()
   * @generated
   * @ordered
   */
  protected EList<Identificador> ids;

  /**
   * The cached value of the '{@link #getTipoParam() <em>Tipo Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoParam()
   * @generated
   * @ordered
   */
  protected TipoEstendido tipoParam;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParametroImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5fPackage.Literals.PARAMETRO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Identificador> getIds()
  {
    if (ids == null)
    {
      ids = new EObjectContainmentEList<Identificador>(Identificador.class, this, T5fPackage.PARAMETRO__IDS);
    }
    return ids;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TipoEstendido getTipoParam()
  {
    return tipoParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipoParam(TipoEstendido newTipoParam, NotificationChain msgs)
  {
    TipoEstendido oldTipoParam = tipoParam;
    tipoParam = newTipoParam;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.PARAMETRO__TIPO_PARAM, oldTipoParam, newTipoParam);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoParam(TipoEstendido newTipoParam)
  {
    if (newTipoParam != tipoParam)
    {
      NotificationChain msgs = null;
      if (tipoParam != null)
        msgs = ((InternalEObject)tipoParam).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.PARAMETRO__TIPO_PARAM, null, msgs);
      if (newTipoParam != null)
        msgs = ((InternalEObject)newTipoParam).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.PARAMETRO__TIPO_PARAM, null, msgs);
      msgs = basicSetTipoParam(newTipoParam, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.PARAMETRO__TIPO_PARAM, newTipoParam, newTipoParam));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5fPackage.PARAMETRO__IDS:
        return ((InternalEList<?>)getIds()).basicRemove(otherEnd, msgs);
      case T5fPackage.PARAMETRO__TIPO_PARAM:
        return basicSetTipoParam(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5fPackage.PARAMETRO__IDS:
        return getIds();
      case T5fPackage.PARAMETRO__TIPO_PARAM:
        return getTipoParam();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5fPackage.PARAMETRO__IDS:
        getIds().clear();
        getIds().addAll((Collection<? extends Identificador>)newValue);
        return;
      case T5fPackage.PARAMETRO__TIPO_PARAM:
        setTipoParam((TipoEstendido)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.PARAMETRO__IDS:
        getIds().clear();
        return;
      case T5fPackage.PARAMETRO__TIPO_PARAM:
        setTipoParam((TipoEstendido)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.PARAMETRO__IDS:
        return ids != null && !ids.isEmpty();
      case T5fPackage.PARAMETRO__TIPO_PARAM:
        return tipoParam != null;
    }
    return super.eIsSet(featureID);
  }

} //ParametroImpl
