/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Corpo;
import br.ufscar.dc.compiladores.at5.t5f.Declaracao;
import br.ufscar.dc.compiladores.at5.t5f.Programa;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Programa</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ProgramaImpl#getDeclaracoes <em>Declaracoes</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.ProgramaImpl#getCorpo <em>Corpo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramaImpl extends MinimalEObjectImpl.Container implements Programa
{
  /**
   * The cached value of the '{@link #getDeclaracoes() <em>Declaracoes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaracoes()
   * @generated
   * @ordered
   */
  protected EList<Declaracao> declaracoes;

  /**
   * The cached value of the '{@link #getCorpo() <em>Corpo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorpo()
   * @generated
   * @ordered
   */
  protected Corpo corpo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5fPackage.Literals.PROGRAMA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Declaracao> getDeclaracoes()
  {
    if (declaracoes == null)
    {
      declaracoes = new EObjectContainmentEList<Declaracao>(Declaracao.class, this, T5fPackage.PROGRAMA__DECLARACOES);
    }
    return declaracoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Corpo getCorpo()
  {
    return corpo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCorpo(Corpo newCorpo, NotificationChain msgs)
  {
    Corpo oldCorpo = corpo;
    corpo = newCorpo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.PROGRAMA__CORPO, oldCorpo, newCorpo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCorpo(Corpo newCorpo)
  {
    if (newCorpo != corpo)
    {
      NotificationChain msgs = null;
      if (corpo != null)
        msgs = ((InternalEObject)corpo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.PROGRAMA__CORPO, null, msgs);
      if (newCorpo != null)
        msgs = ((InternalEObject)newCorpo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.PROGRAMA__CORPO, null, msgs);
      msgs = basicSetCorpo(newCorpo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.PROGRAMA__CORPO, newCorpo, newCorpo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5fPackage.PROGRAMA__DECLARACOES:
        return ((InternalEList<?>)getDeclaracoes()).basicRemove(otherEnd, msgs);
      case T5fPackage.PROGRAMA__CORPO:
        return basicSetCorpo(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5fPackage.PROGRAMA__DECLARACOES:
        return getDeclaracoes();
      case T5fPackage.PROGRAMA__CORPO:
        return getCorpo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5fPackage.PROGRAMA__DECLARACOES:
        getDeclaracoes().clear();
        getDeclaracoes().addAll((Collection<? extends Declaracao>)newValue);
        return;
      case T5fPackage.PROGRAMA__CORPO:
        setCorpo((Corpo)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.PROGRAMA__DECLARACOES:
        getDeclaracoes().clear();
        return;
      case T5fPackage.PROGRAMA__CORPO:
        setCorpo((Corpo)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.PROGRAMA__DECLARACOES:
        return declaracoes != null && !declaracoes.isEmpty();
      case T5fPackage.PROGRAMA__CORPO:
        return corpo != null;
    }
    return super.eIsSet(featureID);
  }

} //ProgramaImpl
