/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class T5fFactoryImpl extends EFactoryImpl implements T5fFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static T5fFactory init()
  {
    try
    {
      T5fFactory theT5fFactory = (T5fFactory)EPackage.Registry.INSTANCE.getEFactory(T5fPackage.eNS_URI);
      if (theT5fFactory != null)
      {
        return theT5fFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new T5fFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public T5fFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case T5fPackage.PROGRAMA: return createPrograma();
      case T5fPackage.DECLARACAO: return createDeclaracao();
      case T5fPackage.DECLARACAO_LOCAL: return createDeclaracaoLocal();
      case T5fPackage.DECLARACAO_GLOBAL: return createDeclaracaoGlobal();
      case T5fPackage.VARIAVEL: return createVariavel();
      case T5fPackage.IDENTIFICADOR: return createIdentificador();
      case T5fPackage.DIMENSAO: return createDimensao();
      case T5fPackage.TIPO: return createTipo();
      case T5fPackage.REGISTRO: return createRegistro();
      case T5fPackage.TIPO_ESTENDIDO: return createTipoEstendido();
      case T5fPackage.PARAMETROS: return createParametros();
      case T5fPackage.PARAMETRO: return createParametro();
      case T5fPackage.CORPO: return createCorpo();
      case T5fPackage.COMANDO: return createComando();
      case T5fPackage.COMANDO_LEIA: return createComandoLeia();
      case T5fPackage.COMANDO_ESCREVA: return createComandoEscreva();
      case T5fPackage.COMANDO_SE: return createComandoSe();
      case T5fPackage.COMANDO_CASO: return createComandoCaso();
      case T5fPackage.COMANDO_PARA: return createComandoPara();
      case T5fPackage.COMANDO_ENQUANTO: return createComandoEnquanto();
      case T5fPackage.COMANDO_FACA: return createComandoFaca();
      case T5fPackage.COMANDO_ATRIBUICAO: return createComandoAtribuicao();
      case T5fPackage.COMANDO_CHAMADA: return createComandoChamada();
      case T5fPackage.COMANDO_RETORNE: return createComandoRetorne();
      case T5fPackage.SELECAO: return createSelecao();
      case T5fPackage.ITEM_SELECAO: return createItemSelecao();
      case T5fPackage.NUMERO_INTERVALO: return createNumeroIntervalo();
      case T5fPackage.EXPRESSAO_ARITMETICA: return createExpressaoAritmetica();
      case T5fPackage.OUTRO_TERMO_ARITMETICO: return createOutroTermoAritmetico();
      case T5fPackage.TERMO_ARITMETICO: return createTermoAritmetico();
      case T5fPackage.OUTRO_FATOR_ARITMETICO: return createOutroFatorAritmetico();
      case T5fPackage.FATOR_ARITMETICO: return createFatorAritmetico();
      case T5fPackage.EXPRESSAO: return createExpressao();
      case T5fPackage.TERMO_LOGICO: return createTermoLogico();
      case T5fPackage.EXPRESSAO_RELACIONAL: return createExpressaoRelacional();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Programa createPrograma()
  {
    ProgramaImpl programa = new ProgramaImpl();
    return programa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declaracao createDeclaracao()
  {
    DeclaracaoImpl declaracao = new DeclaracaoImpl();
    return declaracao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclaracaoLocal createDeclaracaoLocal()
  {
    DeclaracaoLocalImpl declaracaoLocal = new DeclaracaoLocalImpl();
    return declaracaoLocal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclaracaoGlobal createDeclaracaoGlobal()
  {
    DeclaracaoGlobalImpl declaracaoGlobal = new DeclaracaoGlobalImpl();
    return declaracaoGlobal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variavel createVariavel()
  {
    VariavelImpl variavel = new VariavelImpl();
    return variavel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Identificador createIdentificador()
  {
    IdentificadorImpl identificador = new IdentificadorImpl();
    return identificador;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dimensao createDimensao()
  {
    DimensaoImpl dimensao = new DimensaoImpl();
    return dimensao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Tipo createTipo()
  {
    TipoImpl tipo = new TipoImpl();
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Registro createRegistro()
  {
    RegistroImpl registro = new RegistroImpl();
    return registro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TipoEstendido createTipoEstendido()
  {
    TipoEstendidoImpl tipoEstendido = new TipoEstendidoImpl();
    return tipoEstendido;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Parametros createParametros()
  {
    ParametrosImpl parametros = new ParametrosImpl();
    return parametros;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Parametro createParametro()
  {
    ParametroImpl parametro = new ParametroImpl();
    return parametro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Corpo createCorpo()
  {
    CorpoImpl corpo = new CorpoImpl();
    return corpo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comando createComando()
  {
    ComandoImpl comando = new ComandoImpl();
    return comando;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoLeia createComandoLeia()
  {
    ComandoLeiaImpl comandoLeia = new ComandoLeiaImpl();
    return comandoLeia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoEscreva createComandoEscreva()
  {
    ComandoEscrevaImpl comandoEscreva = new ComandoEscrevaImpl();
    return comandoEscreva;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoSe createComandoSe()
  {
    ComandoSeImpl comandoSe = new ComandoSeImpl();
    return comandoSe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoCaso createComandoCaso()
  {
    ComandoCasoImpl comandoCaso = new ComandoCasoImpl();
    return comandoCaso;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoPara createComandoPara()
  {
    ComandoParaImpl comandoPara = new ComandoParaImpl();
    return comandoPara;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoEnquanto createComandoEnquanto()
  {
    ComandoEnquantoImpl comandoEnquanto = new ComandoEnquantoImpl();
    return comandoEnquanto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoFaca createComandoFaca()
  {
    ComandoFacaImpl comandoFaca = new ComandoFacaImpl();
    return comandoFaca;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoAtribuicao createComandoAtribuicao()
  {
    ComandoAtribuicaoImpl comandoAtribuicao = new ComandoAtribuicaoImpl();
    return comandoAtribuicao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoChamada createComandoChamada()
  {
    ComandoChamadaImpl comandoChamada = new ComandoChamadaImpl();
    return comandoChamada;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoRetorne createComandoRetorne()
  {
    ComandoRetorneImpl comandoRetorne = new ComandoRetorneImpl();
    return comandoRetorne;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Selecao createSelecao()
  {
    SelecaoImpl selecao = new SelecaoImpl();
    return selecao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ItemSelecao createItemSelecao()
  {
    ItemSelecaoImpl itemSelecao = new ItemSelecaoImpl();
    return itemSelecao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumeroIntervalo createNumeroIntervalo()
  {
    NumeroIntervaloImpl numeroIntervalo = new NumeroIntervaloImpl();
    return numeroIntervalo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoAritmetica createExpressaoAritmetica()
  {
    ExpressaoAritmeticaImpl expressaoAritmetica = new ExpressaoAritmeticaImpl();
    return expressaoAritmetica;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroTermoAritmetico createOutroTermoAritmetico()
  {
    OutroTermoAritmeticoImpl outroTermoAritmetico = new OutroTermoAritmeticoImpl();
    return outroTermoAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoAritmetico createTermoAritmetico()
  {
    TermoAritmeticoImpl termoAritmetico = new TermoAritmeticoImpl();
    return termoAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroFatorAritmetico createOutroFatorAritmetico()
  {
    OutroFatorAritmeticoImpl outroFatorAritmetico = new OutroFatorAritmeticoImpl();
    return outroFatorAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorAritmetico createFatorAritmetico()
  {
    FatorAritmeticoImpl fatorAritmetico = new FatorAritmeticoImpl();
    return fatorAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expressao createExpressao()
  {
    ExpressaoImpl expressao = new ExpressaoImpl();
    return expressao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoLogico createTermoLogico()
  {
    TermoLogicoImpl termoLogico = new TermoLogicoImpl();
    return termoLogico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoRelacional createExpressaoRelacional()
  {
    ExpressaoRelacionalImpl expressaoRelacional = new ExpressaoRelacionalImpl();
    return expressaoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public T5fPackage getT5fPackage()
  {
    return (T5fPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static T5fPackage getPackage()
  {
    return T5fPackage.eINSTANCE;
  }

} //T5fFactoryImpl
