/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Comando;
import br.ufscar.dc.compiladores.at5.t5f.ComandoAtribuicao;
import br.ufscar.dc.compiladores.at5.t5f.ComandoCaso;
import br.ufscar.dc.compiladores.at5.t5f.ComandoChamada;
import br.ufscar.dc.compiladores.at5.t5f.ComandoEnquanto;
import br.ufscar.dc.compiladores.at5.t5f.ComandoEscreva;
import br.ufscar.dc.compiladores.at5.t5f.ComandoFaca;
import br.ufscar.dc.compiladores.at5.t5f.ComandoLeia;
import br.ufscar.dc.compiladores.at5.t5f.ComandoPara;
import br.ufscar.dc.compiladores.at5.t5f.ComandoRetorne;
import br.ufscar.dc.compiladores.at5.t5f.ComandoSe;
import br.ufscar.dc.compiladores.at5.t5f.Corpo;
import br.ufscar.dc.compiladores.at5.t5f.Declaracao;
import br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal;
import br.ufscar.dc.compiladores.at5.t5f.DeclaracaoLocal;
import br.ufscar.dc.compiladores.at5.t5f.Dimensao;
import br.ufscar.dc.compiladores.at5.t5f.Expressao;
import br.ufscar.dc.compiladores.at5.t5f.ExpressaoAritmetica;
import br.ufscar.dc.compiladores.at5.t5f.ExpressaoRelacional;
import br.ufscar.dc.compiladores.at5.t5f.FatorAritmetico;
import br.ufscar.dc.compiladores.at5.t5f.Identificador;
import br.ufscar.dc.compiladores.at5.t5f.ItemSelecao;
import br.ufscar.dc.compiladores.at5.t5f.NumeroIntervalo;
import br.ufscar.dc.compiladores.at5.t5f.OutroFatorAritmetico;
import br.ufscar.dc.compiladores.at5.t5f.OutroTermoAritmetico;
import br.ufscar.dc.compiladores.at5.t5f.Parametro;
import br.ufscar.dc.compiladores.at5.t5f.Parametros;
import br.ufscar.dc.compiladores.at5.t5f.Programa;
import br.ufscar.dc.compiladores.at5.t5f.Registro;
import br.ufscar.dc.compiladores.at5.t5f.Selecao;
import br.ufscar.dc.compiladores.at5.t5f.T5fFactory;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;
import br.ufscar.dc.compiladores.at5.t5f.TermoAritmetico;
import br.ufscar.dc.compiladores.at5.t5f.TermoLogico;
import br.ufscar.dc.compiladores.at5.t5f.Tipo;
import br.ufscar.dc.compiladores.at5.t5f.TipoEstendido;
import br.ufscar.dc.compiladores.at5.t5f.Variavel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class T5fPackageImpl extends EPackageImpl implements T5fPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass programaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaracaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaracaoLocalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaracaoGlobalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variavelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass identificadorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dimensaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tipoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass registroEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tipoEstendidoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parametrosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parametroEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass corpoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoLeiaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoEscrevaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoSeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoCasoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoParaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoEnquantoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoFacaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoAtribuicaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoChamadaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comandoRetorneEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass selecaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass itemSelecaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass numeroIntervaloEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressaoAritmeticaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass outroTermoAritmeticoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass termoAritmeticoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass outroFatorAritmeticoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fatorAritmeticoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass termoLogicoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressaoRelacionalEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private T5fPackageImpl()
  {
    super(eNS_URI, T5fFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link T5fPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static T5fPackage init()
  {
    if (isInited) return (T5fPackage)EPackage.Registry.INSTANCE.getEPackage(T5fPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredT5fPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    T5fPackageImpl theT5fPackage = registeredT5fPackage instanceof T5fPackageImpl ? (T5fPackageImpl)registeredT5fPackage : new T5fPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theT5fPackage.createPackageContents();

    // Initialize created meta-data
    theT5fPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theT5fPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(T5fPackage.eNS_URI, theT5fPackage);
    return theT5fPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPrograma()
  {
    return programaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPrograma_Declaracoes()
  {
    return (EReference)programaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPrograma_Corpo()
  {
    return (EReference)programaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclaracao()
  {
    return declaracaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclaracao_Name()
  {
    return (EAttribute)declaracaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclaracaoLocal()
  {
    return declaracaoLocalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclaracaoLocal_Variaveis()
  {
    return (EReference)declaracaoLocalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclaracaoLocal_TipoBasico()
  {
    return (EAttribute)declaracaoLocalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclaracaoLocal_Valor()
  {
    return (EAttribute)declaracaoLocalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclaracaoLocal_TipoDef()
  {
    return (EReference)declaracaoLocalEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclaracaoGlobal()
  {
    return declaracaoGlobalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclaracaoGlobal_Parametros()
  {
    return (EReference)declaracaoGlobalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclaracaoGlobal_Corpo()
  {
    return (EReference)declaracaoGlobalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclaracaoGlobal_TipoRetorno()
  {
    return (EReference)declaracaoGlobalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariavel()
  {
    return variavelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVariavel_Name()
  {
    return (EReference)variavelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVariavel_TipoVar()
  {
    return (EReference)variavelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIdentificador()
  {
    return identificadorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIdentificador_Name()
  {
    return (EAttribute)identificadorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIdentificador_Parts()
  {
    return (EAttribute)identificadorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIdentificador_Dimensoes()
  {
    return (EReference)identificadorEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDimensao()
  {
    return dimensaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDimensao_Exp()
  {
    return (EReference)dimensaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTipo()
  {
    return tipoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTipo_Registro()
  {
    return (EReference)tipoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTipo_TipoExt()
  {
    return (EReference)tipoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRegistro()
  {
    return registroEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRegistro_Campos()
  {
    return (EReference)registroEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTipoEstendido()
  {
    return tipoEstendidoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTipoEstendido_Basic()
  {
    return (EAttribute)tipoEstendidoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTipoEstendido_Ref()
  {
    return (EReference)tipoEstendidoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParametros()
  {
    return parametrosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParametros_Parametro()
  {
    return (EReference)parametrosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParametro()
  {
    return parametroEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParametro_Ids()
  {
    return (EReference)parametroEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParametro_TipoParam()
  {
    return (EReference)parametroEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCorpo()
  {
    return corpoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCorpo_Locais()
  {
    return (EReference)corpoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCorpo_Comandos()
  {
    return (EReference)corpoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComando()
  {
    return comandoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoLeia()
  {
    return comandoLeiaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoLeia_Alvo()
  {
    return (EReference)comandoLeiaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoEscreva()
  {
    return comandoEscrevaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoEscreva_Exp()
  {
    return (EReference)comandoEscrevaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoSe()
  {
    return comandoSeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoSe_Cond()
  {
    return (EReference)comandoSeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoSe_Comandos()
  {
    return (EReference)comandoSeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoSe_ComandosElse()
  {
    return (EReference)comandoSeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoCaso()
  {
    return comandoCasoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoCaso_Exp()
  {
    return (EReference)comandoCasoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoCaso_Selecao()
  {
    return (EReference)comandoCasoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoCaso_ComandosElse()
  {
    return (EReference)comandoCasoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoPara()
  {
    return comandoParaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComandoPara_Var()
  {
    return (EAttribute)comandoParaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoPara_Inicio()
  {
    return (EReference)comandoParaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoPara_Fim()
  {
    return (EReference)comandoParaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoPara_Comandos()
  {
    return (EReference)comandoParaEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoEnquanto()
  {
    return comandoEnquantoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoEnquanto_Cond()
  {
    return (EReference)comandoEnquantoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoEnquanto_Comandos()
  {
    return (EReference)comandoEnquantoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoFaca()
  {
    return comandoFacaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoFaca_Comandos()
  {
    return (EReference)comandoFacaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoFaca_Cond()
  {
    return (EReference)comandoFacaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoAtribuicao()
  {
    return comandoAtribuicaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoAtribuicao_Target()
  {
    return (EReference)comandoAtribuicaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoAtribuicao_Valor()
  {
    return (EReference)comandoAtribuicaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoChamada()
  {
    return comandoChamadaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComandoChamada_Name()
  {
    return (EAttribute)comandoChamadaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoChamada_Args()
  {
    return (EReference)comandoChamadaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComandoRetorne()
  {
    return comandoRetorneEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComandoRetorne_Exp()
  {
    return (EReference)comandoRetorneEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSelecao()
  {
    return selecaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSelecao_Itens()
  {
    return (EReference)selecaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSelecao_Comandos()
  {
    return (EReference)selecaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getItemSelecao()
  {
    return itemSelecaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getItemSelecao_Faixas()
  {
    return (EReference)itemSelecaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNumeroIntervalo()
  {
    return numeroIntervaloEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNumeroIntervalo_Sinal()
  {
    return (EAttribute)numeroIntervaloEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNumeroIntervalo_Start()
  {
    return (EAttribute)numeroIntervaloEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNumeroIntervalo_End()
  {
    return (EAttribute)numeroIntervaloEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExpressaoAritmetica()
  {
    return expressaoAritmeticaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExpressaoAritmetica_Termos()
  {
    return (EReference)expressaoAritmeticaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExpressaoAritmetica_Outros()
  {
    return (EReference)expressaoAritmeticaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOutroTermoAritmetico()
  {
    return outroTermoAritmeticoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOutroTermoAritmetico_Op()
  {
    return (EAttribute)outroTermoAritmeticoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOutroTermoAritmetico_Termo()
  {
    return (EReference)outroTermoAritmeticoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTermoAritmetico()
  {
    return termoAritmeticoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTermoAritmetico_Fatores()
  {
    return (EReference)termoAritmeticoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTermoAritmetico_Outros()
  {
    return (EReference)termoAritmeticoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOutroFatorAritmetico()
  {
    return outroFatorAritmeticoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOutroFatorAritmetico_Op()
  {
    return (EAttribute)outroFatorAritmeticoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOutroFatorAritmetico_Fator()
  {
    return (EReference)outroFatorAritmeticoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFatorAritmetico()
  {
    return fatorAritmeticoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFatorAritmetico_Ref()
  {
    return (EReference)fatorAritmeticoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFatorAritmetico_Numero()
  {
    return (EAttribute)fatorAritmeticoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFatorAritmetico_Real()
  {
    return (EAttribute)fatorAritmeticoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFatorAritmetico_Exp()
  {
    return (EReference)fatorAritmeticoEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFatorAritmetico_Str()
  {
    return (EAttribute)fatorAritmeticoEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExpressao()
  {
    return expressaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExpressao_Logicos()
  {
    return (EReference)expressaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExpressao_Op()
  {
    return (EAttribute)expressaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTermoLogico()
  {
    return termoLogicoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTermoLogico_Nao()
  {
    return (EAttribute)termoLogicoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTermoLogico_Rel()
  {
    return (EReference)termoLogicoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExpressaoRelacional()
  {
    return expressaoRelacionalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExpressaoRelacional_Left()
  {
    return (EReference)expressaoRelacionalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExpressaoRelacional_Op()
  {
    return (EAttribute)expressaoRelacionalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExpressaoRelacional_Right()
  {
    return (EReference)expressaoRelacionalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public T5fFactory getT5fFactory()
  {
    return (T5fFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    programaEClass = createEClass(PROGRAMA);
    createEReference(programaEClass, PROGRAMA__DECLARACOES);
    createEReference(programaEClass, PROGRAMA__CORPO);

    declaracaoEClass = createEClass(DECLARACAO);
    createEAttribute(declaracaoEClass, DECLARACAO__NAME);

    declaracaoLocalEClass = createEClass(DECLARACAO_LOCAL);
    createEReference(declaracaoLocalEClass, DECLARACAO_LOCAL__VARIAVEIS);
    createEAttribute(declaracaoLocalEClass, DECLARACAO_LOCAL__TIPO_BASICO);
    createEAttribute(declaracaoLocalEClass, DECLARACAO_LOCAL__VALOR);
    createEReference(declaracaoLocalEClass, DECLARACAO_LOCAL__TIPO_DEF);

    declaracaoGlobalEClass = createEClass(DECLARACAO_GLOBAL);
    createEReference(declaracaoGlobalEClass, DECLARACAO_GLOBAL__PARAMETROS);
    createEReference(declaracaoGlobalEClass, DECLARACAO_GLOBAL__CORPO);
    createEReference(declaracaoGlobalEClass, DECLARACAO_GLOBAL__TIPO_RETORNO);

    variavelEClass = createEClass(VARIAVEL);
    createEReference(variavelEClass, VARIAVEL__NAME);
    createEReference(variavelEClass, VARIAVEL__TIPO_VAR);

    identificadorEClass = createEClass(IDENTIFICADOR);
    createEAttribute(identificadorEClass, IDENTIFICADOR__NAME);
    createEAttribute(identificadorEClass, IDENTIFICADOR__PARTS);
    createEReference(identificadorEClass, IDENTIFICADOR__DIMENSOES);

    dimensaoEClass = createEClass(DIMENSAO);
    createEReference(dimensaoEClass, DIMENSAO__EXP);

    tipoEClass = createEClass(TIPO);
    createEReference(tipoEClass, TIPO__REGISTRO);
    createEReference(tipoEClass, TIPO__TIPO_EXT);

    registroEClass = createEClass(REGISTRO);
    createEReference(registroEClass, REGISTRO__CAMPOS);

    tipoEstendidoEClass = createEClass(TIPO_ESTENDIDO);
    createEAttribute(tipoEstendidoEClass, TIPO_ESTENDIDO__BASIC);
    createEReference(tipoEstendidoEClass, TIPO_ESTENDIDO__REF);

    parametrosEClass = createEClass(PARAMETROS);
    createEReference(parametrosEClass, PARAMETROS__PARAMETRO);

    parametroEClass = createEClass(PARAMETRO);
    createEReference(parametroEClass, PARAMETRO__IDS);
    createEReference(parametroEClass, PARAMETRO__TIPO_PARAM);

    corpoEClass = createEClass(CORPO);
    createEReference(corpoEClass, CORPO__LOCAIS);
    createEReference(corpoEClass, CORPO__COMANDOS);

    comandoEClass = createEClass(COMANDO);

    comandoLeiaEClass = createEClass(COMANDO_LEIA);
    createEReference(comandoLeiaEClass, COMANDO_LEIA__ALVO);

    comandoEscrevaEClass = createEClass(COMANDO_ESCREVA);
    createEReference(comandoEscrevaEClass, COMANDO_ESCREVA__EXP);

    comandoSeEClass = createEClass(COMANDO_SE);
    createEReference(comandoSeEClass, COMANDO_SE__COND);
    createEReference(comandoSeEClass, COMANDO_SE__COMANDOS);
    createEReference(comandoSeEClass, COMANDO_SE__COMANDOS_ELSE);

    comandoCasoEClass = createEClass(COMANDO_CASO);
    createEReference(comandoCasoEClass, COMANDO_CASO__EXP);
    createEReference(comandoCasoEClass, COMANDO_CASO__SELECAO);
    createEReference(comandoCasoEClass, COMANDO_CASO__COMANDOS_ELSE);

    comandoParaEClass = createEClass(COMANDO_PARA);
    createEAttribute(comandoParaEClass, COMANDO_PARA__VAR);
    createEReference(comandoParaEClass, COMANDO_PARA__INICIO);
    createEReference(comandoParaEClass, COMANDO_PARA__FIM);
    createEReference(comandoParaEClass, COMANDO_PARA__COMANDOS);

    comandoEnquantoEClass = createEClass(COMANDO_ENQUANTO);
    createEReference(comandoEnquantoEClass, COMANDO_ENQUANTO__COND);
    createEReference(comandoEnquantoEClass, COMANDO_ENQUANTO__COMANDOS);

    comandoFacaEClass = createEClass(COMANDO_FACA);
    createEReference(comandoFacaEClass, COMANDO_FACA__COMANDOS);
    createEReference(comandoFacaEClass, COMANDO_FACA__COND);

    comandoAtribuicaoEClass = createEClass(COMANDO_ATRIBUICAO);
    createEReference(comandoAtribuicaoEClass, COMANDO_ATRIBUICAO__TARGET);
    createEReference(comandoAtribuicaoEClass, COMANDO_ATRIBUICAO__VALOR);

    comandoChamadaEClass = createEClass(COMANDO_CHAMADA);
    createEAttribute(comandoChamadaEClass, COMANDO_CHAMADA__NAME);
    createEReference(comandoChamadaEClass, COMANDO_CHAMADA__ARGS);

    comandoRetorneEClass = createEClass(COMANDO_RETORNE);
    createEReference(comandoRetorneEClass, COMANDO_RETORNE__EXP);

    selecaoEClass = createEClass(SELECAO);
    createEReference(selecaoEClass, SELECAO__ITENS);
    createEReference(selecaoEClass, SELECAO__COMANDOS);

    itemSelecaoEClass = createEClass(ITEM_SELECAO);
    createEReference(itemSelecaoEClass, ITEM_SELECAO__FAIXAS);

    numeroIntervaloEClass = createEClass(NUMERO_INTERVALO);
    createEAttribute(numeroIntervaloEClass, NUMERO_INTERVALO__SINAL);
    createEAttribute(numeroIntervaloEClass, NUMERO_INTERVALO__START);
    createEAttribute(numeroIntervaloEClass, NUMERO_INTERVALO__END);

    expressaoAritmeticaEClass = createEClass(EXPRESSAO_ARITMETICA);
    createEReference(expressaoAritmeticaEClass, EXPRESSAO_ARITMETICA__TERMOS);
    createEReference(expressaoAritmeticaEClass, EXPRESSAO_ARITMETICA__OUTROS);

    outroTermoAritmeticoEClass = createEClass(OUTRO_TERMO_ARITMETICO);
    createEAttribute(outroTermoAritmeticoEClass, OUTRO_TERMO_ARITMETICO__OP);
    createEReference(outroTermoAritmeticoEClass, OUTRO_TERMO_ARITMETICO__TERMO);

    termoAritmeticoEClass = createEClass(TERMO_ARITMETICO);
    createEReference(termoAritmeticoEClass, TERMO_ARITMETICO__FATORES);
    createEReference(termoAritmeticoEClass, TERMO_ARITMETICO__OUTROS);

    outroFatorAritmeticoEClass = createEClass(OUTRO_FATOR_ARITMETICO);
    createEAttribute(outroFatorAritmeticoEClass, OUTRO_FATOR_ARITMETICO__OP);
    createEReference(outroFatorAritmeticoEClass, OUTRO_FATOR_ARITMETICO__FATOR);

    fatorAritmeticoEClass = createEClass(FATOR_ARITMETICO);
    createEReference(fatorAritmeticoEClass, FATOR_ARITMETICO__REF);
    createEAttribute(fatorAritmeticoEClass, FATOR_ARITMETICO__NUMERO);
    createEAttribute(fatorAritmeticoEClass, FATOR_ARITMETICO__REAL);
    createEReference(fatorAritmeticoEClass, FATOR_ARITMETICO__EXP);
    createEAttribute(fatorAritmeticoEClass, FATOR_ARITMETICO__STR);

    expressaoEClass = createEClass(EXPRESSAO);
    createEReference(expressaoEClass, EXPRESSAO__LOGICOS);
    createEAttribute(expressaoEClass, EXPRESSAO__OP);

    termoLogicoEClass = createEClass(TERMO_LOGICO);
    createEAttribute(termoLogicoEClass, TERMO_LOGICO__NAO);
    createEReference(termoLogicoEClass, TERMO_LOGICO__REL);

    expressaoRelacionalEClass = createEClass(EXPRESSAO_RELACIONAL);
    createEReference(expressaoRelacionalEClass, EXPRESSAO_RELACIONAL__LEFT);
    createEAttribute(expressaoRelacionalEClass, EXPRESSAO_RELACIONAL__OP);
    createEReference(expressaoRelacionalEClass, EXPRESSAO_RELACIONAL__RIGHT);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    declaracaoLocalEClass.getESuperTypes().add(this.getDeclaracao());
    declaracaoGlobalEClass.getESuperTypes().add(this.getDeclaracao());
    comandoLeiaEClass.getESuperTypes().add(this.getComando());
    comandoEscrevaEClass.getESuperTypes().add(this.getComando());
    comandoSeEClass.getESuperTypes().add(this.getComando());
    comandoCasoEClass.getESuperTypes().add(this.getComando());
    comandoParaEClass.getESuperTypes().add(this.getComando());
    comandoEnquantoEClass.getESuperTypes().add(this.getComando());
    comandoFacaEClass.getESuperTypes().add(this.getComando());
    comandoAtribuicaoEClass.getESuperTypes().add(this.getComando());
    comandoChamadaEClass.getESuperTypes().add(this.getComando());
    comandoRetorneEClass.getESuperTypes().add(this.getComando());

    // Initialize classes and features; add operations and parameters
    initEClass(programaEClass, Programa.class, "Programa", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPrograma_Declaracoes(), this.getDeclaracao(), null, "declaracoes", null, 0, -1, Programa.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPrograma_Corpo(), this.getCorpo(), null, "corpo", null, 0, 1, Programa.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declaracaoEClass, Declaracao.class, "Declaracao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeclaracao_Name(), ecorePackage.getEString(), "name", null, 0, 1, Declaracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declaracaoLocalEClass, DeclaracaoLocal.class, "DeclaracaoLocal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclaracaoLocal_Variaveis(), this.getVariavel(), null, "variaveis", null, 0, -1, DeclaracaoLocal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDeclaracaoLocal_TipoBasico(), ecorePackage.getEString(), "tipoBasico", null, 0, 1, DeclaracaoLocal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDeclaracaoLocal_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, DeclaracaoLocal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclaracaoLocal_TipoDef(), this.getTipo(), null, "tipoDef", null, 0, 1, DeclaracaoLocal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declaracaoGlobalEClass, DeclaracaoGlobal.class, "DeclaracaoGlobal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclaracaoGlobal_Parametros(), this.getParametros(), null, "parametros", null, 0, 1, DeclaracaoGlobal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclaracaoGlobal_Corpo(), this.getCorpo(), null, "corpo", null, 0, 1, DeclaracaoGlobal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclaracaoGlobal_TipoRetorno(), this.getTipoEstendido(), null, "tipoRetorno", null, 0, 1, DeclaracaoGlobal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variavelEClass, Variavel.class, "Variavel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVariavel_Name(), this.getIdentificador(), null, "name", null, 0, 1, Variavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVariavel_TipoVar(), this.getTipo(), null, "tipoVar", null, 0, 1, Variavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(identificadorEClass, Identificador.class, "Identificador", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIdentificador_Name(), ecorePackage.getEString(), "name", null, 0, 1, Identificador.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIdentificador_Parts(), ecorePackage.getEString(), "parts", null, 0, -1, Identificador.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIdentificador_Dimensoes(), this.getDimensao(), null, "dimensoes", null, 0, -1, Identificador.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dimensaoEClass, Dimensao.class, "Dimensao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDimensao_Exp(), this.getExpressaoAritmetica(), null, "exp", null, 0, 1, Dimensao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(tipoEClass, Tipo.class, "Tipo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTipo_Registro(), this.getRegistro(), null, "registro", null, 0, 1, Tipo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTipo_TipoExt(), this.getTipoEstendido(), null, "tipoExt", null, 0, 1, Tipo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(registroEClass, Registro.class, "Registro", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRegistro_Campos(), this.getVariavel(), null, "campos", null, 0, -1, Registro.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(tipoEstendidoEClass, TipoEstendido.class, "TipoEstendido", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTipoEstendido_Basic(), ecorePackage.getEString(), "basic", null, 0, 1, TipoEstendido.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTipoEstendido_Ref(), this.getDeclaracao(), null, "ref", null, 0, 1, TipoEstendido.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parametrosEClass, Parametros.class, "Parametros", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParametros_Parametro(), this.getParametro(), null, "parametro", null, 0, -1, Parametros.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parametroEClass, Parametro.class, "Parametro", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParametro_Ids(), this.getIdentificador(), null, "ids", null, 0, -1, Parametro.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getParametro_TipoParam(), this.getTipoEstendido(), null, "tipoParam", null, 0, 1, Parametro.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(corpoEClass, Corpo.class, "Corpo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCorpo_Locais(), this.getDeclaracaoLocal(), null, "locais", null, 0, -1, Corpo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCorpo_Comandos(), this.getComando(), null, "comandos", null, 0, -1, Corpo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoEClass, Comando.class, "Comando", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(comandoLeiaEClass, ComandoLeia.class, "ComandoLeia", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoLeia_Alvo(), this.getVariavel(), null, "alvo", null, 0, -1, ComandoLeia.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoEscrevaEClass, ComandoEscreva.class, "ComandoEscreva", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoEscreva_Exp(), this.getExpressao(), null, "exp", null, 0, -1, ComandoEscreva.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoSeEClass, ComandoSe.class, "ComandoSe", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoSe_Cond(), this.getExpressao(), null, "cond", null, 0, 1, ComandoSe.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSe_Comandos(), this.getComando(), null, "comandos", null, 0, -1, ComandoSe.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoSe_ComandosElse(), this.getComando(), null, "comandosElse", null, 0, -1, ComandoSe.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoCasoEClass, ComandoCaso.class, "ComandoCaso", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoCaso_Exp(), this.getExpressaoAritmetica(), null, "exp", null, 0, 1, ComandoCaso.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoCaso_Selecao(), this.getSelecao(), null, "selecao", null, 0, -1, ComandoCaso.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoCaso_ComandosElse(), this.getComando(), null, "comandosElse", null, 0, -1, ComandoCaso.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoParaEClass, ComandoPara.class, "ComandoPara", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComandoPara_Var(), ecorePackage.getEString(), "var", null, 0, 1, ComandoPara.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoPara_Inicio(), this.getExpressaoAritmetica(), null, "inicio", null, 0, 1, ComandoPara.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoPara_Fim(), this.getExpressaoAritmetica(), null, "fim", null, 0, 1, ComandoPara.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoPara_Comandos(), this.getComando(), null, "comandos", null, 0, -1, ComandoPara.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoEnquantoEClass, ComandoEnquanto.class, "ComandoEnquanto", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoEnquanto_Cond(), this.getExpressao(), null, "cond", null, 0, 1, ComandoEnquanto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoEnquanto_Comandos(), this.getComando(), null, "comandos", null, 0, -1, ComandoEnquanto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoFacaEClass, ComandoFaca.class, "ComandoFaca", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoFaca_Comandos(), this.getComando(), null, "comandos", null, 0, -1, ComandoFaca.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoFaca_Cond(), this.getExpressao(), null, "cond", null, 0, 1, ComandoFaca.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoAtribuicaoEClass, ComandoAtribuicao.class, "ComandoAtribuicao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoAtribuicao_Target(), this.getVariavel(), null, "target", null, 0, 1, ComandoAtribuicao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoAtribuicao_Valor(), this.getExpressao(), null, "valor", null, 0, 1, ComandoAtribuicao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoChamadaEClass, ComandoChamada.class, "ComandoChamada", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComandoChamada_Name(), ecorePackage.getEString(), "name", null, 0, 1, ComandoChamada.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComandoChamada_Args(), this.getExpressao(), null, "args", null, 0, -1, ComandoChamada.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comandoRetorneEClass, ComandoRetorne.class, "ComandoRetorne", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComandoRetorne_Exp(), this.getExpressao(), null, "exp", null, 0, 1, ComandoRetorne.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(selecaoEClass, Selecao.class, "Selecao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSelecao_Itens(), this.getItemSelecao(), null, "itens", null, 0, -1, Selecao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSelecao_Comandos(), this.getComando(), null, "comandos", null, 0, -1, Selecao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(itemSelecaoEClass, ItemSelecao.class, "ItemSelecao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getItemSelecao_Faixas(), this.getNumeroIntervalo(), null, "faixas", null, 0, -1, ItemSelecao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(numeroIntervaloEClass, NumeroIntervalo.class, "NumeroIntervalo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNumeroIntervalo_Sinal(), ecorePackage.getEBoolean(), "sinal", null, 0, 1, NumeroIntervalo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNumeroIntervalo_Start(), ecorePackage.getEInt(), "start", null, 0, 1, NumeroIntervalo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNumeroIntervalo_End(), ecorePackage.getEInt(), "end", null, 0, 1, NumeroIntervalo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressaoAritmeticaEClass, ExpressaoAritmetica.class, "ExpressaoAritmetica", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpressaoAritmetica_Termos(), this.getTermoAritmetico(), null, "termos", null, 0, -1, ExpressaoAritmetica.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpressaoAritmetica_Outros(), this.getOutroTermoAritmetico(), null, "outros", null, 0, -1, ExpressaoAritmetica.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(outroTermoAritmeticoEClass, OutroTermoAritmetico.class, "OutroTermoAritmetico", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOutroTermoAritmetico_Op(), ecorePackage.getEString(), "op", null, 0, 1, OutroTermoAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOutroTermoAritmetico_Termo(), this.getTermoAritmetico(), null, "termo", null, 0, 1, OutroTermoAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(termoAritmeticoEClass, TermoAritmetico.class, "TermoAritmetico", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTermoAritmetico_Fatores(), this.getFatorAritmetico(), null, "fatores", null, 0, -1, TermoAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTermoAritmetico_Outros(), this.getOutroFatorAritmetico(), null, "outros", null, 0, -1, TermoAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(outroFatorAritmeticoEClass, OutroFatorAritmetico.class, "OutroFatorAritmetico", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOutroFatorAritmetico_Op(), ecorePackage.getEString(), "op", null, 0, 1, OutroFatorAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOutroFatorAritmetico_Fator(), this.getFatorAritmetico(), null, "fator", null, 0, 1, OutroFatorAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fatorAritmeticoEClass, FatorAritmetico.class, "FatorAritmetico", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFatorAritmetico_Ref(), this.getVariavel(), null, "ref", null, 0, 1, FatorAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFatorAritmetico_Numero(), ecorePackage.getEInt(), "numero", null, 0, 1, FatorAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFatorAritmetico_Real(), ecorePackage.getEString(), "real", null, 0, 1, FatorAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFatorAritmetico_Exp(), this.getExpressaoAritmetica(), null, "exp", null, 0, 1, FatorAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFatorAritmetico_Str(), ecorePackage.getEString(), "str", null, 0, 1, FatorAritmetico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressaoEClass, Expressao.class, "Expressao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpressao_Logicos(), this.getTermoLogico(), null, "logicos", null, 0, -1, Expressao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExpressao_Op(), ecorePackage.getEString(), "op", null, 0, -1, Expressao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(termoLogicoEClass, TermoLogico.class, "TermoLogico", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTermoLogico_Nao(), ecorePackage.getEBoolean(), "nao", null, 0, 1, TermoLogico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTermoLogico_Rel(), this.getExpressaoRelacional(), null, "rel", null, 0, 1, TermoLogico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressaoRelacionalEClass, ExpressaoRelacional.class, "ExpressaoRelacional", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpressaoRelacional_Left(), this.getExpressaoAritmetica(), null, "left", null, 0, 1, ExpressaoRelacional.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExpressaoRelacional_Op(), ecorePackage.getEString(), "op", null, 0, 1, ExpressaoRelacional.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpressaoRelacional_Right(), this.getExpressaoAritmetica(), null, "right", null, 0, 1, ExpressaoRelacional.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //T5fPackageImpl
