/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Registro;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;
import br.ufscar.dc.compiladores.at5.t5f.Tipo;
import br.ufscar.dc.compiladores.at5.t5f.TipoEstendido;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tipo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.TipoImpl#getRegistro <em>Registro</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.TipoImpl#getTipoExt <em>Tipo Ext</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TipoImpl extends MinimalEObjectImpl.Container implements Tipo
{
  /**
   * The cached value of the '{@link #getRegistro() <em>Registro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegistro()
   * @generated
   * @ordered
   */
  protected Registro registro;

  /**
   * The cached value of the '{@link #getTipoExt() <em>Tipo Ext</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoExt()
   * @generated
   * @ordered
   */
  protected TipoEstendido tipoExt;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TipoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5fPackage.Literals.TIPO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Registro getRegistro()
  {
    return registro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRegistro(Registro newRegistro, NotificationChain msgs)
  {
    Registro oldRegistro = registro;
    registro = newRegistro;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.TIPO__REGISTRO, oldRegistro, newRegistro);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRegistro(Registro newRegistro)
  {
    if (newRegistro != registro)
    {
      NotificationChain msgs = null;
      if (registro != null)
        msgs = ((InternalEObject)registro).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.TIPO__REGISTRO, null, msgs);
      if (newRegistro != null)
        msgs = ((InternalEObject)newRegistro).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.TIPO__REGISTRO, null, msgs);
      msgs = basicSetRegistro(newRegistro, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.TIPO__REGISTRO, newRegistro, newRegistro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TipoEstendido getTipoExt()
  {
    return tipoExt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipoExt(TipoEstendido newTipoExt, NotificationChain msgs)
  {
    TipoEstendido oldTipoExt = tipoExt;
    tipoExt = newTipoExt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.TIPO__TIPO_EXT, oldTipoExt, newTipoExt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoExt(TipoEstendido newTipoExt)
  {
    if (newTipoExt != tipoExt)
    {
      NotificationChain msgs = null;
      if (tipoExt != null)
        msgs = ((InternalEObject)tipoExt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.TIPO__TIPO_EXT, null, msgs);
      if (newTipoExt != null)
        msgs = ((InternalEObject)newTipoExt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.TIPO__TIPO_EXT, null, msgs);
      msgs = basicSetTipoExt(newTipoExt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.TIPO__TIPO_EXT, newTipoExt, newTipoExt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5fPackage.TIPO__REGISTRO:
        return basicSetRegistro(null, msgs);
      case T5fPackage.TIPO__TIPO_EXT:
        return basicSetTipoExt(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5fPackage.TIPO__REGISTRO:
        return getRegistro();
      case T5fPackage.TIPO__TIPO_EXT:
        return getTipoExt();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5fPackage.TIPO__REGISTRO:
        setRegistro((Registro)newValue);
        return;
      case T5fPackage.TIPO__TIPO_EXT:
        setTipoExt((TipoEstendido)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.TIPO__REGISTRO:
        setRegistro((Registro)null);
        return;
      case T5fPackage.TIPO__TIPO_EXT:
        setTipoExt((TipoEstendido)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.TIPO__REGISTRO:
        return registro != null;
      case T5fPackage.TIPO__TIPO_EXT:
        return tipoExt != null;
    }
    return super.eIsSet(featureID);
  }

} //TipoImpl
