/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.impl;

import br.ufscar.dc.compiladores.at5.t5f.Identificador;
import br.ufscar.dc.compiladores.at5.t5f.T5fPackage;
import br.ufscar.dc.compiladores.at5.t5f.Tipo;
import br.ufscar.dc.compiladores.at5.t5f.Variavel;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variavel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.VariavelImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.at5.t5f.impl.VariavelImpl#getTipoVar <em>Tipo Var</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VariavelImpl extends MinimalEObjectImpl.Container implements Variavel
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected Identificador name;

  /**
   * The cached value of the '{@link #getTipoVar() <em>Tipo Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoVar()
   * @generated
   * @ordered
   */
  protected Tipo tipoVar;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VariavelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5fPackage.Literals.VARIAVEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Identificador getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(Identificador newName, NotificationChain msgs)
  {
    Identificador oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.VARIAVEL__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(Identificador newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.VARIAVEL__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.VARIAVEL__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.VARIAVEL__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Tipo getTipoVar()
  {
    return tipoVar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipoVar(Tipo newTipoVar, NotificationChain msgs)
  {
    Tipo oldTipoVar = tipoVar;
    tipoVar = newTipoVar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5fPackage.VARIAVEL__TIPO_VAR, oldTipoVar, newTipoVar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoVar(Tipo newTipoVar)
  {
    if (newTipoVar != tipoVar)
    {
      NotificationChain msgs = null;
      if (tipoVar != null)
        msgs = ((InternalEObject)tipoVar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5fPackage.VARIAVEL__TIPO_VAR, null, msgs);
      if (newTipoVar != null)
        msgs = ((InternalEObject)newTipoVar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5fPackage.VARIAVEL__TIPO_VAR, null, msgs);
      msgs = basicSetTipoVar(newTipoVar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5fPackage.VARIAVEL__TIPO_VAR, newTipoVar, newTipoVar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5fPackage.VARIAVEL__NAME:
        return basicSetName(null, msgs);
      case T5fPackage.VARIAVEL__TIPO_VAR:
        return basicSetTipoVar(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5fPackage.VARIAVEL__NAME:
        return getName();
      case T5fPackage.VARIAVEL__TIPO_VAR:
        return getTipoVar();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5fPackage.VARIAVEL__NAME:
        setName((Identificador)newValue);
        return;
      case T5fPackage.VARIAVEL__TIPO_VAR:
        setTipoVar((Tipo)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.VARIAVEL__NAME:
        setName((Identificador)null);
        return;
      case T5fPackage.VARIAVEL__TIPO_VAR:
        setTipoVar((Tipo)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5fPackage.VARIAVEL__NAME:
        return name != null;
      case T5fPackage.VARIAVEL__TIPO_VAR:
        return tipoVar != null;
    }
    return super.eIsSet(featureID);
  }

} //VariavelImpl
