/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.ide.contentassist.antlr;

import br.ufscar.dc.compiladores.t5.ide.contentassist.antlr.internal.InternalT5Parser;
import br.ufscar.dc.compiladores.t5.services.T5GrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class T5Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(T5GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, T5GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDeclaracaoAccess().getAlternatives(), "rule__Declaracao__Alternatives");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getAlternatives(), "rule__DeclaracaoLocal__Alternatives");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getAlternatives(), "rule__DeclaracaoGlobal__Alternatives");
			builder.put(grammarAccess.getTipoAccess().getAlternatives(), "rule__Tipo__Alternatives");
			builder.put(grammarAccess.getTipoEstendidoAccess().getAlternatives_1(), "rule__TipoEstendido__Alternatives_1");
			builder.put(grammarAccess.getTipoBasicoAccess().getAlternatives(), "rule__TipoBasico__Alternatives");
			builder.put(grammarAccess.getValorConstanteAccess().getAlternatives(), "rule__ValorConstante__Alternatives");
			builder.put(grammarAccess.getComandoAccess().getAlternatives(), "rule__Comando__Alternatives");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getAlternatives(), "rule__FatorAritmetico__Alternatives");
			builder.put(grammarAccess.getOpArit1Access().getAlternatives(), "rule__OpArit1__Alternatives");
			builder.put(grammarAccess.getOpArit2Access().getAlternatives(), "rule__OpArit2__Alternatives");
			builder.put(grammarAccess.getOpRelAccess().getAlternatives(), "rule__OpRel__Alternatives");
			builder.put(grammarAccess.getOpBoolAccess().getAlternatives(), "rule__OpBool__Alternatives");
			builder.put(grammarAccess.getProgramaAccess().getGroup(), "rule__Programa__Group__0");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getGroup_0(), "rule__DeclaracaoLocal__Group_0__0");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getGroup_0_2(), "rule__DeclaracaoLocal__Group_0_2__0");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getGroup_1(), "rule__DeclaracaoLocal__Group_1__0");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getGroup_2(), "rule__DeclaracaoLocal__Group_2__0");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getGroup_0(), "rule__DeclaracaoGlobal__Group_0__0");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getGroup_1(), "rule__DeclaracaoGlobal__Group_1__0");
			builder.put(grammarAccess.getVariavelAccess().getGroup(), "rule__Variavel__Group__0");
			builder.put(grammarAccess.getIdentificadorAccess().getGroup(), "rule__Identificador__Group__0");
			builder.put(grammarAccess.getIdentificadorAccess().getGroup_1(), "rule__Identificador__Group_1__0");
			builder.put(grammarAccess.getDimensaoAccess().getGroup(), "rule__Dimensao__Group__0");
			builder.put(grammarAccess.getRegistroAccess().getGroup(), "rule__Registro__Group__0");
			builder.put(grammarAccess.getTipoEstendidoAccess().getGroup(), "rule__TipoEstendido__Group__0");
			builder.put(grammarAccess.getParametrosAccess().getGroup(), "rule__Parametros__Group__0");
			builder.put(grammarAccess.getParametrosAccess().getGroup_1(), "rule__Parametros__Group_1__0");
			builder.put(grammarAccess.getParametroAccess().getGroup(), "rule__Parametro__Group__0");
			builder.put(grammarAccess.getParametroAccess().getGroup_2(), "rule__Parametro__Group_2__0");
			builder.put(grammarAccess.getCorpoAccess().getGroup(), "rule__Corpo__Group__0");
			builder.put(grammarAccess.getComandoLeiaAccess().getGroup(), "rule__ComandoLeia__Group__0");
			builder.put(grammarAccess.getComandoLeiaAccess().getGroup_4(), "rule__ComandoLeia__Group_4__0");
			builder.put(grammarAccess.getComandoEscrevaAccess().getGroup(), "rule__ComandoEscreva__Group__0");
			builder.put(grammarAccess.getComandoEscrevaAccess().getGroup_3(), "rule__ComandoEscreva__Group_3__0");
			builder.put(grammarAccess.getComandoSeAccess().getGroup(), "rule__ComandoSe__Group__0");
			builder.put(grammarAccess.getComandoSeAccess().getGroup_4(), "rule__ComandoSe__Group_4__0");
			builder.put(grammarAccess.getComandoCasoAccess().getGroup(), "rule__ComandoCaso__Group__0");
			builder.put(grammarAccess.getComandoCasoAccess().getGroup_4(), "rule__ComandoCaso__Group_4__0");
			builder.put(grammarAccess.getComandoParaAccess().getGroup(), "rule__ComandoPara__Group__0");
			builder.put(grammarAccess.getComandoEnquantoAccess().getGroup(), "rule__ComandoEnquanto__Group__0");
			builder.put(grammarAccess.getComandoFacaAccess().getGroup(), "rule__ComandoFaca__Group__0");
			builder.put(grammarAccess.getComandoAtribuicaoAccess().getGroup(), "rule__ComandoAtribuicao__Group__0");
			builder.put(grammarAccess.getComandoChamadaAccess().getGroup(), "rule__ComandoChamada__Group__0");
			builder.put(grammarAccess.getComandoChamadaAccess().getGroup_3(), "rule__ComandoChamada__Group_3__0");
			builder.put(grammarAccess.getComandoChamadaAccess().getGroup_3_1(), "rule__ComandoChamada__Group_3_1__0");
			builder.put(grammarAccess.getComandoRetorneAccess().getGroup(), "rule__ComandoRetorne__Group__0");
			builder.put(grammarAccess.getSelecaoAccess().getGroup(), "rule__Selecao__Group__0");
			builder.put(grammarAccess.getItemSelecaoAccess().getGroup(), "rule__ItemSelecao__Group__0");
			builder.put(grammarAccess.getItemSelecaoAccess().getGroup_1(), "rule__ItemSelecao__Group_1__0");
			builder.put(grammarAccess.getNumeroIntervaloAccess().getGroup(), "rule__NumeroIntervalo__Group__0");
			builder.put(grammarAccess.getNumeroIntervaloAccess().getGroup_2(), "rule__NumeroIntervalo__Group_2__0");
			builder.put(grammarAccess.getExpressaoAritmeticaAccess().getGroup(), "rule__ExpressaoAritmetica__Group__0");
			builder.put(grammarAccess.getOutroTermoAritmeticoAccess().getGroup(), "rule__OutroTermoAritmetico__Group__0");
			builder.put(grammarAccess.getTermoAritmeticoAccess().getGroup(), "rule__TermoAritmetico__Group__0");
			builder.put(grammarAccess.getOutroFatorAritmeticoAccess().getGroup(), "rule__OutroFatorAritmetico__Group__0");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getGroup_0(), "rule__FatorAritmetico__Group_0__0");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getGroup_3(), "rule__FatorAritmetico__Group_3__0");
			builder.put(grammarAccess.getExpressaoAccess().getGroup(), "rule__Expressao__Group__0");
			builder.put(grammarAccess.getExpressaoAccess().getGroup_1(), "rule__Expressao__Group_1__0");
			builder.put(grammarAccess.getTermoLogicoAccess().getGroup(), "rule__TermoLogico__Group__0");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getGroup(), "rule__ExpressaoRelacional__Group__0");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getGroup_1(), "rule__ExpressaoRelacional__Group_1__0");
			builder.put(grammarAccess.getProgramaAccess().getDeclaracoesAssignment_1(), "rule__Programa__DeclaracoesAssignment_1");
			builder.put(grammarAccess.getProgramaAccess().getCorpoAssignment_3(), "rule__Programa__CorpoAssignment_3");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getVariaveisAssignment_0_1(), "rule__DeclaracaoLocal__VariaveisAssignment_0_1");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getVariaveisAssignment_0_2_1(), "rule__DeclaracaoLocal__VariaveisAssignment_0_2_1");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getNameAssignment_1_1(), "rule__DeclaracaoLocal__NameAssignment_1_1");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getTipoBasicoAssignment_1_3(), "rule__DeclaracaoLocal__TipoBasicoAssignment_1_3");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getValorAssignment_1_5(), "rule__DeclaracaoLocal__ValorAssignment_1_5");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getNameAssignment_2_1(), "rule__DeclaracaoLocal__NameAssignment_2_1");
			builder.put(grammarAccess.getDeclaracaoLocalAccess().getTipoDefAssignment_2_3(), "rule__DeclaracaoLocal__TipoDefAssignment_2_3");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getNameAssignment_0_1(), "rule__DeclaracaoGlobal__NameAssignment_0_1");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getParametrosAssignment_0_3(), "rule__DeclaracaoGlobal__ParametrosAssignment_0_3");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getCorpoAssignment_0_5(), "rule__DeclaracaoGlobal__CorpoAssignment_0_5");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getNameAssignment_1_1(), "rule__DeclaracaoGlobal__NameAssignment_1_1");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getParametrosAssignment_1_3(), "rule__DeclaracaoGlobal__ParametrosAssignment_1_3");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getTipoRetornoAssignment_1_6(), "rule__DeclaracaoGlobal__TipoRetornoAssignment_1_6");
			builder.put(grammarAccess.getDeclaracaoGlobalAccess().getCorpoAssignment_1_7(), "rule__DeclaracaoGlobal__CorpoAssignment_1_7");
			builder.put(grammarAccess.getVariavelAccess().getIdAssignment_0(), "rule__Variavel__IdAssignment_0");
			builder.put(grammarAccess.getVariavelAccess().getTipoVarAssignment_2(), "rule__Variavel__TipoVarAssignment_2");
			builder.put(grammarAccess.getIdentificadorAccess().getNameAssignment_0(), "rule__Identificador__NameAssignment_0");
			builder.put(grammarAccess.getIdentificadorAccess().getPartsAssignment_1_1(), "rule__Identificador__PartsAssignment_1_1");
			builder.put(grammarAccess.getIdentificadorAccess().getDimensoesAssignment_2(), "rule__Identificador__DimensoesAssignment_2");
			builder.put(grammarAccess.getDimensaoAccess().getExpAssignment_1(), "rule__Dimensao__ExpAssignment_1");
			builder.put(grammarAccess.getTipoAccess().getRegistroAssignment_0(), "rule__Tipo__RegistroAssignment_0");
			builder.put(grammarAccess.getTipoAccess().getTipoExtAssignment_1(), "rule__Tipo__TipoExtAssignment_1");
			builder.put(grammarAccess.getRegistroAccess().getCamposAssignment_2(), "rule__Registro__CamposAssignment_2");
			builder.put(grammarAccess.getTipoEstendidoAccess().getBasicAssignment_1_0(), "rule__TipoEstendido__BasicAssignment_1_0");
			builder.put(grammarAccess.getTipoEstendidoAccess().getRefAssignment_1_1(), "rule__TipoEstendido__RefAssignment_1_1");
			builder.put(grammarAccess.getParametrosAccess().getParametroAssignment_0(), "rule__Parametros__ParametroAssignment_0");
			builder.put(grammarAccess.getParametrosAccess().getParametroAssignment_1_1(), "rule__Parametros__ParametroAssignment_1_1");
			builder.put(grammarAccess.getParametroAccess().getIdsAssignment_1(), "rule__Parametro__IdsAssignment_1");
			builder.put(grammarAccess.getParametroAccess().getIdsAssignment_2_1(), "rule__Parametro__IdsAssignment_2_1");
			builder.put(grammarAccess.getParametroAccess().getTipoParamAssignment_4(), "rule__Parametro__TipoParamAssignment_4");
			builder.put(grammarAccess.getCorpoAccess().getLocaisAssignment_1(), "rule__Corpo__LocaisAssignment_1");
			builder.put(grammarAccess.getCorpoAccess().getComandosAssignment_2(), "rule__Corpo__ComandosAssignment_2");
			builder.put(grammarAccess.getComandoLeiaAccess().getAlvoAssignment_3(), "rule__ComandoLeia__AlvoAssignment_3");
			builder.put(grammarAccess.getComandoLeiaAccess().getAlvoAssignment_4_2(), "rule__ComandoLeia__AlvoAssignment_4_2");
			builder.put(grammarAccess.getComandoEscrevaAccess().getExpAssignment_2(), "rule__ComandoEscreva__ExpAssignment_2");
			builder.put(grammarAccess.getComandoEscrevaAccess().getExpAssignment_3_1(), "rule__ComandoEscreva__ExpAssignment_3_1");
			builder.put(grammarAccess.getComandoSeAccess().getCondAssignment_1(), "rule__ComandoSe__CondAssignment_1");
			builder.put(grammarAccess.getComandoSeAccess().getComandosAssignment_3(), "rule__ComandoSe__ComandosAssignment_3");
			builder.put(grammarAccess.getComandoSeAccess().getComandosElseAssignment_4_1(), "rule__ComandoSe__ComandosElseAssignment_4_1");
			builder.put(grammarAccess.getComandoCasoAccess().getExpAssignment_1(), "rule__ComandoCaso__ExpAssignment_1");
			builder.put(grammarAccess.getComandoCasoAccess().getSelecaoAssignment_3(), "rule__ComandoCaso__SelecaoAssignment_3");
			builder.put(grammarAccess.getComandoCasoAccess().getComandosElseAssignment_4_1(), "rule__ComandoCaso__ComandosElseAssignment_4_1");
			builder.put(grammarAccess.getComandoParaAccess().getVarAssignment_1(), "rule__ComandoPara__VarAssignment_1");
			builder.put(grammarAccess.getComandoParaAccess().getInicioAssignment_3(), "rule__ComandoPara__InicioAssignment_3");
			builder.put(grammarAccess.getComandoParaAccess().getFimAssignment_5(), "rule__ComandoPara__FimAssignment_5");
			builder.put(grammarAccess.getComandoParaAccess().getComandosAssignment_7(), "rule__ComandoPara__ComandosAssignment_7");
			builder.put(grammarAccess.getComandoEnquantoAccess().getCondAssignment_1(), "rule__ComandoEnquanto__CondAssignment_1");
			builder.put(grammarAccess.getComandoEnquantoAccess().getComandosAssignment_3(), "rule__ComandoEnquanto__ComandosAssignment_3");
			builder.put(grammarAccess.getComandoFacaAccess().getComandosAssignment_1(), "rule__ComandoFaca__ComandosAssignment_1");
			builder.put(grammarAccess.getComandoFacaAccess().getCondAssignment_3(), "rule__ComandoFaca__CondAssignment_3");
			builder.put(grammarAccess.getComandoAtribuicaoAccess().getTargetAssignment_1(), "rule__ComandoAtribuicao__TargetAssignment_1");
			builder.put(grammarAccess.getComandoAtribuicaoAccess().getValorAssignment_3(), "rule__ComandoAtribuicao__ValorAssignment_3");
			builder.put(grammarAccess.getComandoChamadaAccess().getNameAssignment_1(), "rule__ComandoChamada__NameAssignment_1");
			builder.put(grammarAccess.getComandoChamadaAccess().getArgsAssignment_3_0(), "rule__ComandoChamada__ArgsAssignment_3_0");
			builder.put(grammarAccess.getComandoChamadaAccess().getArgsAssignment_3_1_1(), "rule__ComandoChamada__ArgsAssignment_3_1_1");
			builder.put(grammarAccess.getComandoRetorneAccess().getExpAssignment_1(), "rule__ComandoRetorne__ExpAssignment_1");
			builder.put(grammarAccess.getSelecaoAccess().getItensAssignment_0(), "rule__Selecao__ItensAssignment_0");
			builder.put(grammarAccess.getSelecaoAccess().getComandosAssignment_2(), "rule__Selecao__ComandosAssignment_2");
			builder.put(grammarAccess.getItemSelecaoAccess().getFaixasAssignment_0(), "rule__ItemSelecao__FaixasAssignment_0");
			builder.put(grammarAccess.getItemSelecaoAccess().getFaixasAssignment_1_1(), "rule__ItemSelecao__FaixasAssignment_1_1");
			builder.put(grammarAccess.getNumeroIntervaloAccess().getSinalAssignment_0(), "rule__NumeroIntervalo__SinalAssignment_0");
			builder.put(grammarAccess.getNumeroIntervaloAccess().getStartAssignment_1(), "rule__NumeroIntervalo__StartAssignment_1");
			builder.put(grammarAccess.getNumeroIntervaloAccess().getEndAssignment_2_1(), "rule__NumeroIntervalo__EndAssignment_2_1");
			builder.put(grammarAccess.getExpressaoAritmeticaAccess().getTermosAssignment_0(), "rule__ExpressaoAritmetica__TermosAssignment_0");
			builder.put(grammarAccess.getExpressaoAritmeticaAccess().getOutrosAssignment_1(), "rule__ExpressaoAritmetica__OutrosAssignment_1");
			builder.put(grammarAccess.getOutroTermoAritmeticoAccess().getOpAssignment_0(), "rule__OutroTermoAritmetico__OpAssignment_0");
			builder.put(grammarAccess.getOutroTermoAritmeticoAccess().getTermoAssignment_1(), "rule__OutroTermoAritmetico__TermoAssignment_1");
			builder.put(grammarAccess.getTermoAritmeticoAccess().getFatoresAssignment_0(), "rule__TermoAritmetico__FatoresAssignment_0");
			builder.put(grammarAccess.getTermoAritmeticoAccess().getOutrosAssignment_1(), "rule__TermoAritmetico__OutrosAssignment_1");
			builder.put(grammarAccess.getOutroFatorAritmeticoAccess().getOpAssignment_0(), "rule__OutroFatorAritmetico__OpAssignment_0");
			builder.put(grammarAccess.getOutroFatorAritmeticoAccess().getFatorAssignment_1(), "rule__OutroFatorAritmetico__FatorAssignment_1");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getRefAssignment_0_1(), "rule__FatorAritmetico__RefAssignment_0_1");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getNumeroAssignment_1(), "rule__FatorAritmetico__NumeroAssignment_1");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getRealAssignment_2(), "rule__FatorAritmetico__RealAssignment_2");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getExpAssignment_3_1(), "rule__FatorAritmetico__ExpAssignment_3_1");
			builder.put(grammarAccess.getFatorAritmeticoAccess().getStrAssignment_4(), "rule__FatorAritmetico__StrAssignment_4");
			builder.put(grammarAccess.getExpressaoAccess().getLogicosAssignment_0(), "rule__Expressao__LogicosAssignment_0");
			builder.put(grammarAccess.getExpressaoAccess().getOpAssignment_1_0(), "rule__Expressao__OpAssignment_1_0");
			builder.put(grammarAccess.getExpressaoAccess().getLogicosAssignment_1_1(), "rule__Expressao__LogicosAssignment_1_1");
			builder.put(grammarAccess.getTermoLogicoAccess().getNaoAssignment_0(), "rule__TermoLogico__NaoAssignment_0");
			builder.put(grammarAccess.getTermoLogicoAccess().getRelAssignment_1(), "rule__TermoLogico__RelAssignment_1");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getLeftAssignment_0(), "rule__ExpressaoRelacional__LeftAssignment_0");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getOpAssignment_1_0(), "rule__ExpressaoRelacional__OpAssignment_1_0");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getRightAssignment_1_1(), "rule__ExpressaoRelacional__RightAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private T5GrammarAccess grammarAccess;

	@Override
	protected InternalT5Parser createParser() {
		InternalT5Parser result = new InternalT5Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] {  };
	}

	public T5GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(T5GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
