/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class t5Validator extends AbstractT5Validator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					AlgumaPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
