/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class T5UiModule extends AbstractT5UiModule {

	public T5UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
