/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.ui.tests;

import br.ufscar.dc.compiladores.t5.ui.internal.T5Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class T5UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return T5Activator.getInstance().getInjector("br.ufscar.dc.compiladores.t5.T5");
	}

}
