/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Escreva</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.ComandoEscreva#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoEscreva()
 * @model
 * @generated
 */
public interface ComandoEscreva extends Comando
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expressao)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoEscreva_Exp()
   * @model containment="true"
   * @generated
   */
  Expressao getExp();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.ComandoEscreva#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expressao value);

} // ComandoEscreva
