/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Leia</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.ComandoLeia#getAlvo <em>Alvo</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoLeia()
 * @model
 * @generated
 */
public interface ComandoLeia extends Comando
{
  /**
   * Returns the value of the '<em><b>Alvo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alvo</em>' reference.
   * @see #setAlvo(Declaracao)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoLeia_Alvo()
   * @model
   * @generated
   */
  Declaracao getAlvo();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.ComandoLeia#getAlvo <em>Alvo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alvo</em>' reference.
   * @see #getAlvo()
   * @generated
   */
  void setAlvo(Declaracao value);

} // ComandoLeia
