/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Caso</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.ComandoCaso#getExp <em>Exp</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.ComandoCaso#getSelecao <em>Selecao</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.ComandoCaso#getComandosElse <em>Comandos Else</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoCaso()
 * @model
 * @generated
 */
public interface ComandoCaso extends Comando
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(ExpressaoAritmetica)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoCaso_Exp()
   * @model containment="true"
   * @generated
   */
  ExpressaoAritmetica getExp();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.ComandoCaso#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(ExpressaoAritmetica value);

  /**
   * Returns the value of the '<em><b>Selecao</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.Selecao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selecao</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoCaso_Selecao()
   * @model containment="true"
   * @generated
   */
  EList<Selecao> getSelecao();

  /**
   * Returns the value of the '<em><b>Comandos Else</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos Else</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getComandoCaso_ComandosElse()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandosElse();

} // ComandoCaso
