/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fator Sub Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.FatorSubExpressao#getExpressao <em>Expressao</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getFatorSubExpressao()
 * @model
 * @generated
 */
public interface FatorSubExpressao extends FatorAritmetico
{
  /**
   * Returns the value of the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressao</em>' containment reference.
   * @see #setExpressao(ExpressaoAritmetica)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getFatorSubExpressao_Expressao()
   * @model containment="true"
   * @generated
   */
  ExpressaoAritmetica getExpressao();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.FatorSubExpressao#getExpressao <em>Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressao</em>' containment reference.
   * @see #getExpressao()
   * @generated
   */
  void setExpressao(ExpressaoAritmetica value);

} // FatorSubExpressao
