/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getFatorAritmetico()
 * @model
 * @generated
 */
public interface FatorAritmetico extends EObject
{
} // FatorAritmetico
