/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identificador</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.Identificador#getDimensoes <em>Dimensoes</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getIdentificador()
 * @model
 * @generated
 */
public interface Identificador extends EObject
{
  /**
   * Returns the value of the '<em><b>Dimensoes</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.Dimensao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimensoes</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getIdentificador_Dimensoes()
   * @model containment="true"
   * @generated
   */
  EList<Dimensao> getDimensoes();

} // Identificador
