/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Item Selecao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.ItemSelecao#getFaixas <em>Faixas</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getItemSelecao()
 * @model
 * @generated
 */
public interface ItemSelecao extends EObject
{
  /**
   * Returns the value of the '<em><b>Faixas</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.NumeroIntervalo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Faixas</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getItemSelecao_Faixas()
   * @model containment="true"
   * @generated
   */
  EList<NumeroIntervalo> getFaixas();

} // ItemSelecao
