/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numero Intervalo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.NumeroIntervalo#isSinal <em>Sinal</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.NumeroIntervalo#getStart <em>Start</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.NumeroIntervalo#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getNumeroIntervalo()
 * @model
 * @generated
 */
public interface NumeroIntervalo extends EObject
{
  /**
   * Returns the value of the '<em><b>Sinal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sinal</em>' attribute.
   * @see #setSinal(boolean)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getNumeroIntervalo_Sinal()
   * @model
   * @generated
   */
  boolean isSinal();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.NumeroIntervalo#isSinal <em>Sinal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sinal</em>' attribute.
   * @see #isSinal()
   * @generated
   */
  void setSinal(boolean value);

  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see #setStart(int)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getNumeroIntervalo_Start()
   * @model
   * @generated
   */
  int getStart();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.NumeroIntervalo#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see #getStart()
   * @generated
   */
  void setStart(int value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(int)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getNumeroIntervalo_End()
   * @model
   * @generated
   */
  int getEnd();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.NumeroIntervalo#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(int value);

} // NumeroIntervalo
