/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parametros</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.Parametros#getParametro <em>Parametro</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getParametros()
 * @model
 * @generated
 */
public interface Parametros extends EObject
{
  /**
   * Returns the value of the '<em><b>Parametro</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.Parametro}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametro</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getParametros_Parametro()
   * @model containment="true"
   * @generated
   */
  EList<Parametro> getParametro();

} // Parametros
