/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Algoritmo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.SubAlgoritmo#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getSubAlgoritmo()
 * @model
 * @generated
 */
public interface SubAlgoritmo extends Comando
{
  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getSubAlgoritmo_Comandos()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandos();

} // SubAlgoritmo
