/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termo Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.TermoAritmetico#getFatores <em>Fatores</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.TermoAritmetico#getOutros <em>Outros</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getTermoAritmetico()
 * @model
 * @generated
 */
public interface TermoAritmetico extends EObject
{
  /**
   * Returns the value of the '<em><b>Fatores</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.FatorAritmetico}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fatores</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getTermoAritmetico_Fatores()
   * @model containment="true"
   * @generated
   */
  EList<FatorAritmetico> getFatores();

  /**
   * Returns the value of the '<em><b>Outros</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.t5.t5.OutroFatorAritmetico}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outros</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getTermoAritmetico_Outros()
   * @model containment="true"
   * @generated
   */
  EList<OutroFatorAritmetico> getOutros();

} // TermoAritmetico
