/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tipo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.Tipo#getRegistro <em>Registro</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.Tipo#getTipoExt <em>Tipo Ext</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getTipo()
 * @model
 * @generated
 */
public interface Tipo extends EObject
{
  /**
   * Returns the value of the '<em><b>Registro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registro</em>' containment reference.
   * @see #setRegistro(Registro)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getTipo_Registro()
   * @model containment="true"
   * @generated
   */
  Registro getRegistro();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.Tipo#getRegistro <em>Registro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Registro</em>' containment reference.
   * @see #getRegistro()
   * @generated
   */
  void setRegistro(Registro value);

  /**
   * Returns the value of the '<em><b>Tipo Ext</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Ext</em>' containment reference.
   * @see #setTipoExt(TipoEstendido)
   * @see br.ufscar.dc.compiladores.t5.t5.T5Package#getTipo_TipoExt()
   * @model containment="true"
   * @generated
   */
  TipoEstendido getTipoExt();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.t5.t5.Tipo#getTipoExt <em>Tipo Ext</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Ext</em>' containment reference.
   * @see #getTipoExt()
   * @generated
   */
  void setTipoExt(TipoEstendido value);

} // Tipo
