/*
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractT5Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.ufscar.dc.compiladores.t5.t5.T5Package.eINSTANCE);
		return result;
	}
}
