/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.at5.t5f.util;

import br.ufscar.dc.compiladores.at5.t5f.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see br.ufscar.dc.compiladores.at5.t5f.T5fPackage
 * @generated
 */
public class T5fAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static T5fPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public T5fAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = T5fPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected T5fSwitch<Adapter> modelSwitch =
    new T5fSwitch<Adapter>()
    {
      @Override
      public Adapter casePrograma(Programa object)
      {
        return createProgramaAdapter();
      }
      @Override
      public Adapter caseDeclaracao(Declaracao object)
      {
        return createDeclaracaoAdapter();
      }
      @Override
      public Adapter caseDeclaracaoLocal(DeclaracaoLocal object)
      {
        return createDeclaracaoLocalAdapter();
      }
      @Override
      public Adapter caseDeclaracaoGlobal(DeclaracaoGlobal object)
      {
        return createDeclaracaoGlobalAdapter();
      }
      @Override
      public Adapter caseVariavel(Variavel object)
      {
        return createVariavelAdapter();
      }
      @Override
      public Adapter caseIdentificador(Identificador object)
      {
        return createIdentificadorAdapter();
      }
      @Override
      public Adapter caseDimensao(Dimensao object)
      {
        return createDimensaoAdapter();
      }
      @Override
      public Adapter caseTipo(Tipo object)
      {
        return createTipoAdapter();
      }
      @Override
      public Adapter caseRegistro(Registro object)
      {
        return createRegistroAdapter();
      }
      @Override
      public Adapter caseTipoEstendido(TipoEstendido object)
      {
        return createTipoEstendidoAdapter();
      }
      @Override
      public Adapter caseParametros(Parametros object)
      {
        return createParametrosAdapter();
      }
      @Override
      public Adapter caseParametro(Parametro object)
      {
        return createParametroAdapter();
      }
      @Override
      public Adapter caseCorpo(Corpo object)
      {
        return createCorpoAdapter();
      }
      @Override
      public Adapter caseComando(Comando object)
      {
        return createComandoAdapter();
      }
      @Override
      public Adapter caseComandoLeia(ComandoLeia object)
      {
        return createComandoLeiaAdapter();
      }
      @Override
      public Adapter caseComandoEscreva(ComandoEscreva object)
      {
        return createComandoEscrevaAdapter();
      }
      @Override
      public Adapter caseComandoSe(ComandoSe object)
      {
        return createComandoSeAdapter();
      }
      @Override
      public Adapter caseComandoCaso(ComandoCaso object)
      {
        return createComandoCasoAdapter();
      }
      @Override
      public Adapter caseComandoPara(ComandoPara object)
      {
        return createComandoParaAdapter();
      }
      @Override
      public Adapter caseComandoEnquanto(ComandoEnquanto object)
      {
        return createComandoEnquantoAdapter();
      }
      @Override
      public Adapter caseComandoFaca(ComandoFaca object)
      {
        return createComandoFacaAdapter();
      }
      @Override
      public Adapter caseComandoAtribuicao(ComandoAtribuicao object)
      {
        return createComandoAtribuicaoAdapter();
      }
      @Override
      public Adapter caseComandoChamada(ComandoChamada object)
      {
        return createComandoChamadaAdapter();
      }
      @Override
      public Adapter caseComandoRetorne(ComandoRetorne object)
      {
        return createComandoRetorneAdapter();
      }
      @Override
      public Adapter caseSelecao(Selecao object)
      {
        return createSelecaoAdapter();
      }
      @Override
      public Adapter caseItemSelecao(ItemSelecao object)
      {
        return createItemSelecaoAdapter();
      }
      @Override
      public Adapter caseNumeroIntervalo(NumeroIntervalo object)
      {
        return createNumeroIntervaloAdapter();
      }
      @Override
      public Adapter caseExpressaoAritmetica(ExpressaoAritmetica object)
      {
        return createExpressaoAritmeticaAdapter();
      }
      @Override
      public Adapter caseOutroTermoAritmetico(OutroTermoAritmetico object)
      {
        return createOutroTermoAritmeticoAdapter();
      }
      @Override
      public Adapter caseTermoAritmetico(TermoAritmetico object)
      {
        return createTermoAritmeticoAdapter();
      }
      @Override
      public Adapter caseOutroFatorAritmetico(OutroFatorAritmetico object)
      {
        return createOutroFatorAritmeticoAdapter();
      }
      @Override
      public Adapter caseFatorAritmetico(FatorAritmetico object)
      {
        return createFatorAritmeticoAdapter();
      }
      @Override
      public Adapter caseExpressao(Expressao object)
      {
        return createExpressaoAdapter();
      }
      @Override
      public Adapter caseTermoLogico(TermoLogico object)
      {
        return createTermoLogicoAdapter();
      }
      @Override
      public Adapter caseExpressaoRelacional(ExpressaoRelacional object)
      {
        return createExpressaoRelacionalAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Programa
   * @generated
   */
  public Adapter createProgramaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Declaracao <em>Declaracao</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Declaracao
   * @generated
   */
  public Adapter createDeclaracaoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoLocal <em>Declaracao Local</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.DeclaracaoLocal
   * @generated
   */
  public Adapter createDeclaracaoLocalAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal <em>Declaracao Global</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.DeclaracaoGlobal
   * @generated
   */
  public Adapter createDeclaracaoGlobalAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Variavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Variavel
   * @generated
   */
  public Adapter createVariavelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Identificador <em>Identificador</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Identificador
   * @generated
   */
  public Adapter createIdentificadorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Dimensao <em>Dimensao</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Dimensao
   * @generated
   */
  public Adapter createDimensaoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Tipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Tipo
   * @generated
   */
  public Adapter createTipoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Registro <em>Registro</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Registro
   * @generated
   */
  public Adapter createRegistroAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.TipoEstendido <em>Tipo Estendido</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.TipoEstendido
   * @generated
   */
  public Adapter createTipoEstendidoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Parametros <em>Parametros</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Parametros
   * @generated
   */
  public Adapter createParametrosAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Parametro <em>Parametro</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Parametro
   * @generated
   */
  public Adapter createParametroAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Corpo <em>Corpo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Corpo
   * @generated
   */
  public Adapter createCorpoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Comando <em>Comando</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Comando
   * @generated
   */
  public Adapter createComandoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoLeia <em>Comando Leia</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoLeia
   * @generated
   */
  public Adapter createComandoLeiaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoEscreva <em>Comando Escreva</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoEscreva
   * @generated
   */
  public Adapter createComandoEscrevaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoSe <em>Comando Se</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoSe
   * @generated
   */
  public Adapter createComandoSeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoCaso <em>Comando Caso</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoCaso
   * @generated
   */
  public Adapter createComandoCasoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoPara <em>Comando Para</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoPara
   * @generated
   */
  public Adapter createComandoParaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoEnquanto <em>Comando Enquanto</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoEnquanto
   * @generated
   */
  public Adapter createComandoEnquantoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoFaca <em>Comando Faca</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoFaca
   * @generated
   */
  public Adapter createComandoFacaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoAtribuicao <em>Comando Atribuicao</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoAtribuicao
   * @generated
   */
  public Adapter createComandoAtribuicaoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoChamada <em>Comando Chamada</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoChamada
   * @generated
   */
  public Adapter createComandoChamadaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ComandoRetorne <em>Comando Retorne</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ComandoRetorne
   * @generated
   */
  public Adapter createComandoRetorneAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Selecao <em>Selecao</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Selecao
   * @generated
   */
  public Adapter createSelecaoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ItemSelecao <em>Item Selecao</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ItemSelecao
   * @generated
   */
  public Adapter createItemSelecaoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.NumeroIntervalo <em>Numero Intervalo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.NumeroIntervalo
   * @generated
   */
  public Adapter createNumeroIntervaloAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ExpressaoAritmetica <em>Expressao Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ExpressaoAritmetica
   * @generated
   */
  public Adapter createExpressaoAritmeticaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.OutroTermoAritmetico <em>Outro Termo Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.OutroTermoAritmetico
   * @generated
   */
  public Adapter createOutroTermoAritmeticoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.TermoAritmetico <em>Termo Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.TermoAritmetico
   * @generated
   */
  public Adapter createTermoAritmeticoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.OutroFatorAritmetico <em>Outro Fator Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.OutroFatorAritmetico
   * @generated
   */
  public Adapter createOutroFatorAritmeticoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.FatorAritmetico <em>Fator Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.FatorAritmetico
   * @generated
   */
  public Adapter createFatorAritmeticoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.Expressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.Expressao
   * @generated
   */
  public Adapter createExpressaoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.TermoLogico <em>Termo Logico</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.TermoLogico
   * @generated
   */
  public Adapter createTermoLogicoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link br.ufscar.dc.compiladores.at5.t5f.ExpressaoRelacional <em>Expressao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see br.ufscar.dc.compiladores.at5.t5f.ExpressaoRelacional
   * @generated
   */
  public Adapter createExpressaoRelacionalAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //T5fAdapterFactory
