/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5.impl;

import br.ufscar.dc.compiladores.t5.t5.ComandoLeia;
import br.ufscar.dc.compiladores.t5.t5.T5Package;
import br.ufscar.dc.compiladores.t5.t5.Variavel;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comando Leia</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.ComandoLeiaImpl#getAlvo <em>Alvo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComandoLeiaImpl extends ComandoImpl implements ComandoLeia
{
  /**
   * The cached value of the '{@link #getAlvo() <em>Alvo</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlvo()
   * @generated
   * @ordered
   */
  protected EList<Variavel> alvo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandoLeiaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5Package.Literals.COMANDO_LEIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Variavel> getAlvo()
  {
    if (alvo == null)
    {
      alvo = new EObjectResolvingEList<Variavel>(Variavel.class, this, T5Package.COMANDO_LEIA__ALVO);
    }
    return alvo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        return getAlvo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        getAlvo().clear();
        getAlvo().addAll((Collection<? extends Variavel>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        getAlvo().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        return alvo != null && !alvo.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ComandoLeiaImpl
