/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5.impl;

import br.ufscar.dc.compiladores.t5.t5.Comando;
import br.ufscar.dc.compiladores.t5.t5.ComandoCaso;
import br.ufscar.dc.compiladores.t5.t5.ExpressaoAritmetica;
import br.ufscar.dc.compiladores.t5.t5.Selecao;
import br.ufscar.dc.compiladores.t5.t5.T5Package;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comando Caso</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.ComandoCasoImpl#getExp <em>Exp</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.ComandoCasoImpl#getSelecao <em>Selecao</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.ComandoCasoImpl#getComandosElse <em>Comandos Else</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComandoCasoImpl extends ComandoImpl implements ComandoCaso
{
  /**
   * The cached value of the '{@link #getExp() <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExp()
   * @generated
   * @ordered
   */
  protected ExpressaoAritmetica exp;

  /**
   * The cached value of the '{@link #getSelecao() <em>Selecao</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSelecao()
   * @generated
   * @ordered
   */
  protected EList<Selecao> selecao;

  /**
   * The cached value of the '{@link #getComandosElse() <em>Comandos Else</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandosElse()
   * @generated
   * @ordered
   */
  protected EList<Comando> comandosElse;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandoCasoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5Package.Literals.COMANDO_CASO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoAritmetica getExp()
  {
    return exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExp(ExpressaoAritmetica newExp, NotificationChain msgs)
  {
    ExpressaoAritmetica oldExp = exp;
    exp = newExp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5Package.COMANDO_CASO__EXP, oldExp, newExp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExp(ExpressaoAritmetica newExp)
  {
    if (newExp != exp)
    {
      NotificationChain msgs = null;
      if (exp != null)
        msgs = ((InternalEObject)exp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5Package.COMANDO_CASO__EXP, null, msgs);
      if (newExp != null)
        msgs = ((InternalEObject)newExp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5Package.COMANDO_CASO__EXP, null, msgs);
      msgs = basicSetExp(newExp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5Package.COMANDO_CASO__EXP, newExp, newExp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Selecao> getSelecao()
  {
    if (selecao == null)
    {
      selecao = new EObjectContainmentEList<Selecao>(Selecao.class, this, T5Package.COMANDO_CASO__SELECAO);
    }
    return selecao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getComandosElse()
  {
    if (comandosElse == null)
    {
      comandosElse = new EObjectContainmentEList<Comando>(Comando.class, this, T5Package.COMANDO_CASO__COMANDOS_ELSE);
    }
    return comandosElse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_CASO__EXP:
        return basicSetExp(null, msgs);
      case T5Package.COMANDO_CASO__SELECAO:
        return ((InternalEList<?>)getSelecao()).basicRemove(otherEnd, msgs);
      case T5Package.COMANDO_CASO__COMANDOS_ELSE:
        return ((InternalEList<?>)getComandosElse()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_CASO__EXP:
        return getExp();
      case T5Package.COMANDO_CASO__SELECAO:
        return getSelecao();
      case T5Package.COMANDO_CASO__COMANDOS_ELSE:
        return getComandosElse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_CASO__EXP:
        setExp((ExpressaoAritmetica)newValue);
        return;
      case T5Package.COMANDO_CASO__SELECAO:
        getSelecao().clear();
        getSelecao().addAll((Collection<? extends Selecao>)newValue);
        return;
      case T5Package.COMANDO_CASO__COMANDOS_ELSE:
        getComandosElse().clear();
        getComandosElse().addAll((Collection<? extends Comando>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_CASO__EXP:
        setExp((ExpressaoAritmetica)null);
        return;
      case T5Package.COMANDO_CASO__SELECAO:
        getSelecao().clear();
        return;
      case T5Package.COMANDO_CASO__COMANDOS_ELSE:
        getComandosElse().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_CASO__EXP:
        return exp != null;
      case T5Package.COMANDO_CASO__SELECAO:
        return selecao != null && !selecao.isEmpty();
      case T5Package.COMANDO_CASO__COMANDOS_ELSE:
        return comandosElse != null && !comandosElse.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ComandoCasoImpl
