/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5.impl;

import br.ufscar.dc.compiladores.t5.t5.ComandoLeia;
import br.ufscar.dc.compiladores.t5.t5.Declaracao;
import br.ufscar.dc.compiladores.t5.t5.T5Package;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comando Leia</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.ComandoLeiaImpl#getAlvo <em>Alvo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComandoLeiaImpl extends ComandoImpl implements ComandoLeia
{
  /**
   * The cached value of the '{@link #getAlvo() <em>Alvo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlvo()
   * @generated
   * @ordered
   */
  protected Declaracao alvo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandoLeiaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5Package.Literals.COMANDO_LEIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declaracao getAlvo()
  {
    if (alvo != null && alvo.eIsProxy())
    {
      InternalEObject oldAlvo = (InternalEObject)alvo;
      alvo = (Declaracao)eResolveProxy(oldAlvo);
      if (alvo != oldAlvo)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, T5Package.COMANDO_LEIA__ALVO, oldAlvo, alvo));
      }
    }
    return alvo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Declaracao basicGetAlvo()
  {
    return alvo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlvo(Declaracao newAlvo)
  {
    Declaracao oldAlvo = alvo;
    alvo = newAlvo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5Package.COMANDO_LEIA__ALVO, oldAlvo, alvo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        if (resolve) return getAlvo();
        return basicGetAlvo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        setAlvo((Declaracao)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        setAlvo((Declaracao)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5Package.COMANDO_LEIA__ALVO:
        return alvo != null;
    }
    return super.eIsSet(featureID);
  }

} //ComandoLeiaImpl
