/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5.impl;

import br.ufscar.dc.compiladores.t5.t5.Comando;
import br.ufscar.dc.compiladores.t5.t5.Corpo;
import br.ufscar.dc.compiladores.t5.t5.DeclaracaoLocal;
import br.ufscar.dc.compiladores.t5.t5.T5Package;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Corpo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.CorpoImpl#getLocais <em>Locais</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.CorpoImpl#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CorpoImpl extends MinimalEObjectImpl.Container implements Corpo
{
  /**
   * The cached value of the '{@link #getLocais() <em>Locais</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocais()
   * @generated
   * @ordered
   */
  protected EList<DeclaracaoLocal> locais;

  /**
   * The cached value of the '{@link #getComandos() <em>Comandos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandos()
   * @generated
   * @ordered
   */
  protected EList<Comando> comandos;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CorpoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5Package.Literals.CORPO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DeclaracaoLocal> getLocais()
  {
    if (locais == null)
    {
      locais = new EObjectContainmentEList<DeclaracaoLocal>(DeclaracaoLocal.class, this, T5Package.CORPO__LOCAIS);
    }
    return locais;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getComandos()
  {
    if (comandos == null)
    {
      comandos = new EObjectContainmentEList<Comando>(Comando.class, this, T5Package.CORPO__COMANDOS);
    }
    return comandos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5Package.CORPO__LOCAIS:
        return ((InternalEList<?>)getLocais()).basicRemove(otherEnd, msgs);
      case T5Package.CORPO__COMANDOS:
        return ((InternalEList<?>)getComandos()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5Package.CORPO__LOCAIS:
        return getLocais();
      case T5Package.CORPO__COMANDOS:
        return getComandos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5Package.CORPO__LOCAIS:
        getLocais().clear();
        getLocais().addAll((Collection<? extends DeclaracaoLocal>)newValue);
        return;
      case T5Package.CORPO__COMANDOS:
        getComandos().clear();
        getComandos().addAll((Collection<? extends Comando>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5Package.CORPO__LOCAIS:
        getLocais().clear();
        return;
      case T5Package.CORPO__COMANDOS:
        getComandos().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5Package.CORPO__LOCAIS:
        return locais != null && !locais.isEmpty();
      case T5Package.CORPO__COMANDOS:
        return comandos != null && !comandos.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CorpoImpl
