/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5.impl;

import br.ufscar.dc.compiladores.t5.t5.Dimensao;
import br.ufscar.dc.compiladores.t5.t5.Identificador;
import br.ufscar.dc.compiladores.t5.t5.T5Package;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Identificador</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.IdentificadorImpl#getDimensoes <em>Dimensoes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IdentificadorImpl extends MinimalEObjectImpl.Container implements Identificador
{
  /**
   * The cached value of the '{@link #getDimensoes() <em>Dimensoes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDimensoes()
   * @generated
   * @ordered
   */
  protected EList<Dimensao> dimensoes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IdentificadorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5Package.Literals.IDENTIFICADOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Dimensao> getDimensoes()
  {
    if (dimensoes == null)
    {
      dimensoes = new EObjectContainmentEList<Dimensao>(Dimensao.class, this, T5Package.IDENTIFICADOR__DIMENSOES);
    }
    return dimensoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5Package.IDENTIFICADOR__DIMENSOES:
        return ((InternalEList<?>)getDimensoes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5Package.IDENTIFICADOR__DIMENSOES:
        return getDimensoes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5Package.IDENTIFICADOR__DIMENSOES:
        getDimensoes().clear();
        getDimensoes().addAll((Collection<? extends Dimensao>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5Package.IDENTIFICADOR__DIMENSOES:
        getDimensoes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5Package.IDENTIFICADOR__DIMENSOES:
        return dimensoes != null && !dimensoes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //IdentificadorImpl
