/**
 * generated by Xtext 2.39.0
 */
package br.ufscar.dc.compiladores.t5.t5.impl;

import br.ufscar.dc.compiladores.t5.t5.FatorAritmetico;
import br.ufscar.dc.compiladores.t5.t5.OutroFatorAritmetico;
import br.ufscar.dc.compiladores.t5.t5.T5Package;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Outro Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.OutroFatorAritmeticoImpl#getOp <em>Op</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.t5.t5.impl.OutroFatorAritmeticoImpl#getFator <em>Fator</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OutroFatorAritmeticoImpl extends MinimalEObjectImpl.Container implements OutroFatorAritmetico
{
  /**
   * The default value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected static final String OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected String op = OP_EDEFAULT;

  /**
   * The cached value of the '{@link #getFator() <em>Fator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFator()
   * @generated
   * @ordered
   */
  protected FatorAritmetico fator;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutroFatorAritmeticoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T5Package.Literals.OUTRO_FATOR_ARITMETICO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOp()
  {
    return op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOp(String newOp)
  {
    String oldOp = op;
    op = newOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5Package.OUTRO_FATOR_ARITMETICO__OP, oldOp, op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorAritmetico getFator()
  {
    return fator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFator(FatorAritmetico newFator, NotificationChain msgs)
  {
    FatorAritmetico oldFator = fator;
    fator = newFator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, T5Package.OUTRO_FATOR_ARITMETICO__FATOR, oldFator, newFator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFator(FatorAritmetico newFator)
  {
    if (newFator != fator)
    {
      NotificationChain msgs = null;
      if (fator != null)
        msgs = ((InternalEObject)fator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - T5Package.OUTRO_FATOR_ARITMETICO__FATOR, null, msgs);
      if (newFator != null)
        msgs = ((InternalEObject)newFator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - T5Package.OUTRO_FATOR_ARITMETICO__FATOR, null, msgs);
      msgs = basicSetFator(newFator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, T5Package.OUTRO_FATOR_ARITMETICO__FATOR, newFator, newFator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case T5Package.OUTRO_FATOR_ARITMETICO__FATOR:
        return basicSetFator(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case T5Package.OUTRO_FATOR_ARITMETICO__OP:
        return getOp();
      case T5Package.OUTRO_FATOR_ARITMETICO__FATOR:
        return getFator();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case T5Package.OUTRO_FATOR_ARITMETICO__OP:
        setOp((String)newValue);
        return;
      case T5Package.OUTRO_FATOR_ARITMETICO__FATOR:
        setFator((FatorAritmetico)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case T5Package.OUTRO_FATOR_ARITMETICO__OP:
        setOp(OP_EDEFAULT);
        return;
      case T5Package.OUTRO_FATOR_ARITMETICO__FATOR:
        setFator((FatorAritmetico)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case T5Package.OUTRO_FATOR_ARITMETICO__OP:
        return OP_EDEFAULT == null ? op != null : !OP_EDEFAULT.equals(op);
      case T5Package.OUTRO_FATOR_ARITMETICO__FATOR:
        return fator != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (op: ");
    result.append(op);
    result.append(')');
    return result.toString();
  }

} //OutroFatorAritmeticoImpl
